// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/data-cache/data-cache.proto

package data_cache

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// PointService defines service.
type PointService interface {
	// QueryData @alias=/Point/QueryData   测点数据查询
	QueryData(ctx context.Context, req *ReqQueryData) (*RspQueryData, error)
	// QueryChanged @alias=/Point/QueryChanged 查询变化测点
	QueryChanged(ctx context.Context, req *ReqQueryChanged) (*RspQueryChanged, error)
	// QueryCachedPoint @alias=/Point/QueryCachedPoint 查询缓存的测点
	QueryCachedPoint(ctx context.Context, req *ReqQueryCachedPoint) (*RspQueryCachedPoint, error)
}

func PointService_QueryData_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqQueryData{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PointService).QueryData(ctx, reqbody.(*ReqQueryData))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PointService_QueryChanged_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqQueryChanged{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PointService).QueryChanged(ctx, reqbody.(*ReqQueryChanged))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PointService_QueryCachedPoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqQueryCachedPoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PointService).QueryCachedPoint(ctx, reqbody.(*ReqQueryCachedPoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// PointServer_ServiceDesc descriptor for server.RegisterService.
var PointServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.data.cache.Point",
	HandlerType: ((*PointService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Point/QueryData",
			Func: PointService_QueryData_Handler,
		},
		{
			Name: "/Point/QueryChanged",
			Func: PointService_QueryChanged_Handler,
		},
		{
			Name: "/Point/QueryCachedPoint",
			Func: PointService_QueryCachedPoint_Handler,
		},
		{
			Name: "/tbos.data.cache.Point/QueryData",
			Func: PointService_QueryData_Handler,
		},
		{
			Name: "/tbos.data.cache.Point/QueryChanged",
			Func: PointService_QueryChanged_Handler,
		},
		{
			Name: "/tbos.data.cache.Point/QueryCachedPoint",
			Func: PointService_QueryCachedPoint_Handler,
		},
	},
}

// RegisterPointService registers service.
func RegisterPointService(s server.Service, svr PointService) {
	if err := s.Register(&PointServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Point register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedPoint struct{}

// QueryData @alias=/Point/QueryData   测点数据查询
func (s *UnimplementedPoint) QueryData(ctx context.Context, req *ReqQueryData) (*RspQueryData, error) {
	return nil, errors.New("rpc QueryData of service Point is not implemented")
}

// QueryChanged @alias=/Point/QueryChanged 查询变化测点
func (s *UnimplementedPoint) QueryChanged(ctx context.Context, req *ReqQueryChanged) (*RspQueryChanged, error) {
	return nil, errors.New("rpc QueryChanged of service Point is not implemented")
}

// QueryCachedPoint @alias=/Point/QueryCachedPoint 查询缓存的测点
func (s *UnimplementedPoint) QueryCachedPoint(ctx context.Context, req *ReqQueryCachedPoint) (*RspQueryCachedPoint, error) {
	return nil, errors.New("rpc QueryCachedPoint of service Point is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// PointClientProxy defines service client proxy
type PointClientProxy interface {
	// QueryData @alias=/Point/QueryData   测点数据查询
	QueryData(ctx context.Context, req *ReqQueryData, opts ...client.Option) (rsp *RspQueryData, err error)
	// QueryChanged @alias=/Point/QueryChanged 查询变化测点
	QueryChanged(ctx context.Context, req *ReqQueryChanged, opts ...client.Option) (rsp *RspQueryChanged, err error)
	// QueryCachedPoint @alias=/Point/QueryCachedPoint 查询缓存的测点
	QueryCachedPoint(ctx context.Context, req *ReqQueryCachedPoint, opts ...client.Option) (rsp *RspQueryCachedPoint, err error)
}

type PointClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewPointClientProxy = func(opts ...client.Option) PointClientProxy {
	return &PointClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *PointClientProxyImpl) QueryData(ctx context.Context, req *ReqQueryData, opts ...client.Option) (*RspQueryData, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Point/QueryData")
	msg.WithCalleeServiceName(PointServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Point")
	msg.WithCalleeMethod("QueryData")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspQueryData{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PointClientProxyImpl) QueryChanged(ctx context.Context, req *ReqQueryChanged, opts ...client.Option) (*RspQueryChanged, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Point/QueryChanged")
	msg.WithCalleeServiceName(PointServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Point")
	msg.WithCalleeMethod("QueryChanged")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspQueryChanged{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PointClientProxyImpl) QueryCachedPoint(ctx context.Context, req *ReqQueryCachedPoint, opts ...client.Option) (*RspQueryCachedPoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Point/QueryCachedPoint")
	msg.WithCalleeServiceName(PointServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Point")
	msg.WithCalleeMethod("QueryCachedPoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspQueryCachedPoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
