// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.1
// source: trpcprotocol/data-cache/data-cache.proto

package data_cache

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 质量类型枚举
type QualityType int32

const (
	QualityType_QUALITY_TYPE_NORMAL QualityType = 0 // 正常值
	QualityType_QUALITY_TYPE_BAD    QualityType = 1 // 异常值
	QualityType_QUALITY_TYPE_ALL    QualityType = 2 // 所有值
)

// Enum value maps for QualityType.
var (
	QualityType_name = map[int32]string{
		0: "QUALITY_TYPE_NORMAL",
		1: "QUALITY_TYPE_BAD",
		2: "QUALITY_TYPE_ALL",
	}
	QualityType_value = map[string]int32{
		"QUALITY_TYPE_NORMAL": 0,
		"QUALITY_TYPE_BAD":    1,
		"QUALITY_TYPE_ALL":    2,
	}
)

func (x QualityType) Enum() *QualityType {
	p := new(QualityType)
	*p = x
	return p
}

func (x QualityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QualityType) Descriptor() protoreflect.EnumDescriptor {
	return file_trpcprotocol_data_cache_data_cache_proto_enumTypes[0].Descriptor()
}

func (QualityType) Type() protoreflect.EnumType {
	return &file_trpcprotocol_data_cache_data_cache_proto_enumTypes[0]
}

func (x QualityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QualityType.Descriptor instead.
func (QualityType) EnumDescriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{0}
}

// 测点数据查询请求参数
type ReqQueryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointList   []string    `protobuf:"bytes,1,rep,name=point_list,json=pointList,proto3" json:"point_list,omitempty"`                                         // 需要查询的消息列表
	Begin       int64       `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`                                                                 // 起始时间
	End         int64       `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`                                                                     // 结束时间
	QualityType QualityType `protobuf:"varint,4,opt,name=quality_type,json=qualityType,proto3,enum=tbos.data.cache.QualityType" json:"quality_type,omitempty"` // 质量类型
}

func (x *ReqQueryData) Reset() {
	*x = ReqQueryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryData) ProtoMessage() {}

func (x *ReqQueryData) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryData.ProtoReflect.Descriptor instead.
func (*ReqQueryData) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{0}
}

func (x *ReqQueryData) GetPointList() []string {
	if x != nil {
		return x.PointList
	}
	return nil
}

func (x *ReqQueryData) GetBegin() int64 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *ReqQueryData) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *ReqQueryData) GetQualityType() QualityType {
	if x != nil {
		return x.QualityType
	}
	return QualityType_QUALITY_TYPE_NORMAL
}

// 测点数据查询返回数据
type RspQueryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointMap map[string]*RspQueryData_PointValueList `protobuf:"bytes,1,rep,name=point_map,json=pointMap,proto3" json:"point_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 测点对应的值map
}

func (x *RspQueryData) Reset() {
	*x = RspQueryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspQueryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspQueryData) ProtoMessage() {}

func (x *RspQueryData) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspQueryData.ProtoReflect.Descriptor instead.
func (*RspQueryData) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{1}
}

func (x *RspQueryData) GetPointMap() map[string]*RspQueryData_PointValueList {
	if x != nil {
		return x.PointMap
	}
	return nil
}

// 变化测点查询参数
type ReqQueryChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointList []string `protobuf:"bytes,1,rep,name=point_list,json=pointList,proto3" json:"point_list,omitempty"` // 测点列表
	Begin     int64    `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`                         // 开始时间
}

func (x *ReqQueryChanged) Reset() {
	*x = ReqQueryChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryChanged) ProtoMessage() {}

func (x *ReqQueryChanged) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryChanged.ProtoReflect.Descriptor instead.
func (*ReqQueryChanged) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{2}
}

func (x *ReqQueryChanged) GetPointList() []string {
	if x != nil {
		return x.PointList
	}
	return nil
}

func (x *ReqQueryChanged) GetBegin() int64 {
	if x != nil {
		return x.Begin
	}
	return 0
}

// 变化测点查询返回数据
type RspQueryChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangedMap map[string]int64 `protobuf:"bytes,1,rep,name=changed_map,json=changedMap,proto3" json:"changed_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 各测点最近变化时间
}

func (x *RspQueryChanged) Reset() {
	*x = RspQueryChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspQueryChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspQueryChanged) ProtoMessage() {}

func (x *RspQueryChanged) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspQueryChanged.ProtoReflect.Descriptor instead.
func (*RspQueryChanged) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{3}
}

func (x *RspQueryChanged) GetChangedMap() map[string]int64 {
	if x != nil {
		return x.ChangedMap
	}
	return nil
}

// 查询缓存的测点-查询参数
type ReqQueryCachedPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointList []string `protobuf:"bytes,1,rep,name=point_list,json=pointList,proto3" json:"point_list,omitempty"` // 测点列表
	Page      int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                           // 页码
	Size      int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                           // 页大小
}

func (x *ReqQueryCachedPoint) Reset() {
	*x = ReqQueryCachedPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryCachedPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryCachedPoint) ProtoMessage() {}

func (x *ReqQueryCachedPoint) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryCachedPoint.ProtoReflect.Descriptor instead.
func (*ReqQueryCachedPoint) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{4}
}

func (x *ReqQueryCachedPoint) GetPointList() []string {
	if x != nil {
		return x.PointList
	}
	return nil
}

func (x *ReqQueryCachedPoint) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReqQueryCachedPoint) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 查询缓存的测点-响应数据
type RspQueryCachedPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointList []string `protobuf:"bytes,1,rep,name=point_list,json=pointList,proto3" json:"point_list,omitempty"` // 测点列表
	Total     int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                         // 总数
}

func (x *RspQueryCachedPoint) Reset() {
	*x = RspQueryCachedPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspQueryCachedPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspQueryCachedPoint) ProtoMessage() {}

func (x *RspQueryCachedPoint) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspQueryCachedPoint.ProtoReflect.Descriptor instead.
func (*RspQueryCachedPoint) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{5}
}

func (x *RspQueryCachedPoint) GetPointList() []string {
	if x != nil {
		return x.PointList
	}
	return nil
}

func (x *RspQueryCachedPoint) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 测点值列表
type RspQueryData_PointValueList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 测点值
	Values []*RspQueryData_PointValueList_PointValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // 测点值列表
}

func (x *RspQueryData_PointValueList) Reset() {
	*x = RspQueryData_PointValueList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspQueryData_PointValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspQueryData_PointValueList) ProtoMessage() {}

func (x *RspQueryData_PointValueList) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspQueryData_PointValueList.ProtoReflect.Descriptor instead.
func (*RspQueryData_PointValueList) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RspQueryData_PointValueList) GetValues() []*RspQueryData_PointValueList_PointValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type RspQueryData_PointValueList_PointValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Q int64   `protobuf:"varint,1,opt,name=q,proto3" json:"q,omitempty"`  // 测点质量
	V float64 `protobuf:"fixed64,2,opt,name=v,proto3" json:"v,omitempty"` // 测点值
	T int64   `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"`  // 测点时间
}

func (x *RspQueryData_PointValueList_PointValue) Reset() {
	*x = RspQueryData_PointValueList_PointValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspQueryData_PointValueList_PointValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspQueryData_PointValueList_PointValue) ProtoMessage() {}

func (x *RspQueryData_PointValueList_PointValue) ProtoReflect() protoreflect.Message {
	mi := &file_trpcprotocol_data_cache_data_cache_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspQueryData_PointValueList_PointValue.ProtoReflect.Descriptor instead.
func (*RspQueryData_PointValueList_PointValue) Descriptor() ([]byte, []int) {
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *RspQueryData_PointValueList_PointValue) GetQ() int64 {
	if x != nil {
		return x.Q
	}
	return 0
}

func (x *RspQueryData_PointValueList_PointValue) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *RspQueryData_PointValueList_PointValue) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

var File_trpcprotocol_data_cache_data_cache_proto protoreflect.FileDescriptor

var file_trpcprotocol_data_cache_data_cache_proto_rawDesc = []byte{
	0x0a, 0x28, 0x74, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x2d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74, 0x62, 0x6f, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x0c,
	0x52, 0x65, 0x71, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x65, 0x6e, 0x64, 0x12, 0x3f, 0x0a, 0x0c, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x74, 0x62, 0x6f, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x51, 0x75, 0x61, 0x6c,
	0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x22, 0xdf, 0x02, 0x0a, 0x0c, 0x52, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x6d,
	0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x1a,
	0x69, 0x0a, 0x0d, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x42, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x99, 0x01, 0x0a, 0x0e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x4f, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e,
	0x74, 0x62, 0x6f, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x52, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x36,
	0x0a, 0x0a, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x76, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x01, 0x74, 0x22, 0x46, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x22, 0xa3,
	0x01, 0x0a, 0x0f, 0x52, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x12, 0x51, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x5f, 0x6d, 0x61,
	0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x4d, 0x61, 0x70, 0x1a, 0x3d, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x5c, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x22, 0x4a, 0x0a, 0x13, 0x52, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x2a, 0x52,
	0x0a, 0x0b, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x13, 0x51, 0x55, 0x41, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f,
	0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x51, 0x55, 0x41, 0x4c, 0x49, 0x54,
	0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x41, 0x44, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x51, 0x55, 0x41, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x4c, 0x4c,
	0x10, 0x02, 0x32, 0x86, 0x02, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x49, 0x0a, 0x09,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x2e, 0x74, 0x62, 0x6f, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1d, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x52, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x20, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x1a, 0x20, 0x2e, 0x74, 0x62, 0x6f, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x5e, 0x0a, 0x10, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x24, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x19, 0x5a, 0x17, 0x74,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x2d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trpcprotocol_data_cache_data_cache_proto_rawDescOnce sync.Once
	file_trpcprotocol_data_cache_data_cache_proto_rawDescData = file_trpcprotocol_data_cache_data_cache_proto_rawDesc
)

func file_trpcprotocol_data_cache_data_cache_proto_rawDescGZIP() []byte {
	file_trpcprotocol_data_cache_data_cache_proto_rawDescOnce.Do(func() {
		file_trpcprotocol_data_cache_data_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_trpcprotocol_data_cache_data_cache_proto_rawDescData)
	})
	return file_trpcprotocol_data_cache_data_cache_proto_rawDescData
}

var file_trpcprotocol_data_cache_data_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trpcprotocol_data_cache_data_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_trpcprotocol_data_cache_data_cache_proto_goTypes = []interface{}{
	(QualityType)(0),                               // 0: tbos.data.cache.QualityType
	(*ReqQueryData)(nil),                           // 1: tbos.data.cache.ReqQueryData
	(*RspQueryData)(nil),                           // 2: tbos.data.cache.RspQueryData
	(*ReqQueryChanged)(nil),                        // 3: tbos.data.cache.ReqQueryChanged
	(*RspQueryChanged)(nil),                        // 4: tbos.data.cache.RspQueryChanged
	(*ReqQueryCachedPoint)(nil),                    // 5: tbos.data.cache.ReqQueryCachedPoint
	(*RspQueryCachedPoint)(nil),                    // 6: tbos.data.cache.RspQueryCachedPoint
	nil,                                            // 7: tbos.data.cache.RspQueryData.PointMapEntry
	(*RspQueryData_PointValueList)(nil),            // 8: tbos.data.cache.RspQueryData.PointValueList
	(*RspQueryData_PointValueList_PointValue)(nil), // 9: tbos.data.cache.RspQueryData.PointValueList.PointValue
	nil, // 10: tbos.data.cache.RspQueryChanged.ChangedMapEntry
}
var file_trpcprotocol_data_cache_data_cache_proto_depIdxs = []int32{
	0,  // 0: tbos.data.cache.ReqQueryData.quality_type:type_name -> tbos.data.cache.QualityType
	7,  // 1: tbos.data.cache.RspQueryData.point_map:type_name -> tbos.data.cache.RspQueryData.PointMapEntry
	10, // 2: tbos.data.cache.RspQueryChanged.changed_map:type_name -> tbos.data.cache.RspQueryChanged.ChangedMapEntry
	8,  // 3: tbos.data.cache.RspQueryData.PointMapEntry.value:type_name -> tbos.data.cache.RspQueryData.PointValueList
	9,  // 4: tbos.data.cache.RspQueryData.PointValueList.values:type_name -> tbos.data.cache.RspQueryData.PointValueList.PointValue
	1,  // 5: tbos.data.cache.Point.QueryData:input_type -> tbos.data.cache.ReqQueryData
	3,  // 6: tbos.data.cache.Point.QueryChanged:input_type -> tbos.data.cache.ReqQueryChanged
	5,  // 7: tbos.data.cache.Point.QueryCachedPoint:input_type -> tbos.data.cache.ReqQueryCachedPoint
	2,  // 8: tbos.data.cache.Point.QueryData:output_type -> tbos.data.cache.RspQueryData
	4,  // 9: tbos.data.cache.Point.QueryChanged:output_type -> tbos.data.cache.RspQueryChanged
	6,  // 10: tbos.data.cache.Point.QueryCachedPoint:output_type -> tbos.data.cache.RspQueryCachedPoint
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_trpcprotocol_data_cache_data_cache_proto_init() }
func file_trpcprotocol_data_cache_data_cache_proto_init() {
	if File_trpcprotocol_data_cache_data_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspQueryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspQueryChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryCachedPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspQueryCachedPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspQueryData_PointValueList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trpcprotocol_data_cache_data_cache_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspQueryData_PointValueList_PointValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trpcprotocol_data_cache_data_cache_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trpcprotocol_data_cache_data_cache_proto_goTypes,
		DependencyIndexes: file_trpcprotocol_data_cache_data_cache_proto_depIdxs,
		EnumInfos:         file_trpcprotocol_data_cache_data_cache_proto_enumTypes,
		MessageInfos:      file_trpcprotocol_data_cache_data_cache_proto_msgTypes,
	}.Build()
	File_trpcprotocol_data_cache_data_cache_proto = out.File
	file_trpcprotocol_data_cache_data_cache_proto_rawDesc = nil
	file_trpcprotocol_data_cache_data_cache_proto_goTypes = nil
	file_trpcprotocol_data_cache_data_cache_proto_depIdxs = nil
}
