// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: cmdb.proto

package cmdb

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ConfigBuildService defines service.
type ConfigBuildService interface {
	// SaveMozu @alias=/ConfigBuild/SaveMozu   保存模组信息
	SaveMozu(ctx context.Context, req *ReqSaveMozu) (*emptypb.Empty, error)
	// ListMozu @alias=/ConfigBuild/ListMozu  查询模组信息
	ListMozu(ctx context.Context, req *ReqListMozu) (*RspListMozu, error)
	// DeleteMozu @alias=/ConfigBuild/DeleteMozu  删除模组信息
	DeleteMozu(ctx context.Context, req *ReqDeleteMozu) (*emptypb.Empty, error)
	// ImportModel @alias=/ConfigBuild/ImportModel  导入模组配置信息
	ImportModel(ctx context.Context, req *ReqImportModel) (*RspImportModel, error)
}

func ConfigBuildService_SaveMozu_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqSaveMozu{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigBuildService).SaveMozu(ctx, reqbody.(*ReqSaveMozu))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigBuildService_ListMozu_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqListMozu{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigBuildService).ListMozu(ctx, reqbody.(*ReqListMozu))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigBuildService_DeleteMozu_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqDeleteMozu{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigBuildService).DeleteMozu(ctx, reqbody.(*ReqDeleteMozu))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigBuildService_ImportModel_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqImportModel{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigBuildService).ImportModel(ctx, reqbody.(*ReqImportModel))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ConfigBuildServer_ServiceDesc descriptor for server.RegisterService.
var ConfigBuildServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.cmdb.ConfigBuild",
	HandlerType: ((*ConfigBuildService)(nil)),
	Methods: []server.Method{
		{
			Name: "/ConfigBuild/SaveMozu",
			Func: ConfigBuildService_SaveMozu_Handler,
		},
		{
			Name: "/ConfigBuild/ListMozu",
			Func: ConfigBuildService_ListMozu_Handler,
		},
		{
			Name: "/ConfigBuild/DeleteMozu",
			Func: ConfigBuildService_DeleteMozu_Handler,
		},
		{
			Name: "/ConfigBuild/ImportModel",
			Func: ConfigBuildService_ImportModel_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigBuild/SaveMozu",
			Func: ConfigBuildService_SaveMozu_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigBuild/ListMozu",
			Func: ConfigBuildService_ListMozu_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigBuild/DeleteMozu",
			Func: ConfigBuildService_DeleteMozu_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigBuild/ImportModel",
			Func: ConfigBuildService_ImportModel_Handler,
		},
	},
}

// RegisterConfigBuildService registers service.
func RegisterConfigBuildService(s server.Service, svr ConfigBuildService) {
	if err := s.Register(&ConfigBuildServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ConfigBuild register error:%v", err))
	}
}

// ConfigQueryService defines service.
type ConfigQueryService interface {
	// GetCollectorDevice @alias=/ConfigQuery/GetCollectorDevice   获取采集器下子设备
	GetCollectorDevice(ctx context.Context, req *ReqGetCollectorDevice) (*RspGetCollectorDevice, error)
	// GetCollectorPoint @alias=/ConfigQuery/GetCollectorPoint   获取采集器下的标准测点
	GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint) (*RspGetCollectorPoint, error)
	// GetCollectorTemplate @alias=/ConfigQuery/GetCollectorTemplate   获取采集模版配置信息
	GetCollectorTemplate(ctx context.Context, req *ReqGetCollectorTemplate) (*RspGetCollectorTemplate, error)
	// GetConfigModifyTime @alias=/ConfigQuery/GetConfigModifyTime   获取配置更新时间
	GetConfigModifyTime(ctx context.Context, req *ReqGetCollectorDevice) (*RspGetConfigModifyTime, error)
	// ExportCollectorConfig @alias=/ConfigQuery/ExportCollectorConfig   按模组导出所有的配置
	ExportCollectorConfig(ctx context.Context, req *ReqExportCollectorConfig) (*emptypb.Empty, error)
	// ListCollectorDevice @alias=/ConfigQuery/ListCollectorDevice   获取采集器列表
	ListCollectorDevice(ctx context.Context, req *ReqListCollectorDevice) (*RspListCollectorDevice, error)
	// GetDeviceEntity @alias=/ConfigQuery/GetDeviceEntity   获取标准设备
	GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity) (*RspGetDeviceEntity, error)
	// GetDevicePoint @alias=/ConfigQuery/GetDevicePoint   获取标准测点
	GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint) (*RspGetDevicePoint, error)
	// GetMozuInfo @alias=/ConfigQuery/GetMozuInfo   获取模组信息
	GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo) (*RspGetMozuInfo, error)
}

func ConfigQueryService_GetCollectorDevice_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetCollectorDevice{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).GetCollectorDevice(ctx, reqbody.(*ReqGetCollectorDevice))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_GetCollectorPoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetCollectorPoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).GetCollectorPoint(ctx, reqbody.(*ReqGetCollectorPoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_GetCollectorTemplate_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetCollectorTemplate{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).GetCollectorTemplate(ctx, reqbody.(*ReqGetCollectorTemplate))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_GetConfigModifyTime_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetCollectorDevice{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).GetConfigModifyTime(ctx, reqbody.(*ReqGetCollectorDevice))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_ExportCollectorConfig_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqExportCollectorConfig{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).ExportCollectorConfig(ctx, reqbody.(*ReqExportCollectorConfig))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_ListCollectorDevice_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqListCollectorDevice{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).ListCollectorDevice(ctx, reqbody.(*ReqListCollectorDevice))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_GetDeviceEntity_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetDeviceEntity{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).GetDeviceEntity(ctx, reqbody.(*ReqGetDeviceEntity))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_GetDevicePoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetDevicePoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).GetDevicePoint(ctx, reqbody.(*ReqGetDevicePoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConfigQueryService_GetMozuInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetMozuInfo{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigQueryService).GetMozuInfo(ctx, reqbody.(*ReqGetMozuInfo))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ConfigQueryServer_ServiceDesc descriptor for server.RegisterService.
var ConfigQueryServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.cmdb.ConfigQuery",
	HandlerType: ((*ConfigQueryService)(nil)),
	Methods: []server.Method{
		{
			Name: "/ConfigQuery/GetCollectorDevice",
			Func: ConfigQueryService_GetCollectorDevice_Handler,
		},
		{
			Name: "/ConfigQuery/GetCollectorPoint",
			Func: ConfigQueryService_GetCollectorPoint_Handler,
		},
		{
			Name: "/ConfigQuery/GetCollectorTemplate",
			Func: ConfigQueryService_GetCollectorTemplate_Handler,
		},
		{
			Name: "/ConfigQuery/GetConfigModifyTime",
			Func: ConfigQueryService_GetConfigModifyTime_Handler,
		},
		{
			Name: "/ConfigQuery/ExportCollectorConfig",
			Func: ConfigQueryService_ExportCollectorConfig_Handler,
		},
		{
			Name: "/ConfigQuery/ListCollectorDevice",
			Func: ConfigQueryService_ListCollectorDevice_Handler,
		},
		{
			Name: "/ConfigQuery/GetDeviceEntity",
			Func: ConfigQueryService_GetDeviceEntity_Handler,
		},
		{
			Name: "/ConfigQuery/GetDevicePoint",
			Func: ConfigQueryService_GetDevicePoint_Handler,
		},
		{
			Name: "/ConfigQuery/GetMozuInfo",
			Func: ConfigQueryService_GetMozuInfo_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/GetCollectorDevice",
			Func: ConfigQueryService_GetCollectorDevice_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/GetCollectorPoint",
			Func: ConfigQueryService_GetCollectorPoint_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/GetCollectorTemplate",
			Func: ConfigQueryService_GetCollectorTemplate_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/GetConfigModifyTime",
			Func: ConfigQueryService_GetConfigModifyTime_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/ExportCollectorConfig",
			Func: ConfigQueryService_ExportCollectorConfig_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/ListCollectorDevice",
			Func: ConfigQueryService_ListCollectorDevice_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/GetDeviceEntity",
			Func: ConfigQueryService_GetDeviceEntity_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/GetDevicePoint",
			Func: ConfigQueryService_GetDevicePoint_Handler,
		},
		{
			Name: "/tbos.cmdb.ConfigQuery/GetMozuInfo",
			Func: ConfigQueryService_GetMozuInfo_Handler,
		},
	},
}

// RegisterConfigQueryService registers service.
func RegisterConfigQueryService(s server.Service, svr ConfigQueryService) {
	if err := s.Register(&ConfigQueryServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ConfigQuery register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedConfigBuild struct{}

// SaveMozu @alias=/ConfigBuild/SaveMozu   保存模组信息
func (s *UnimplementedConfigBuild) SaveMozu(ctx context.Context, req *ReqSaveMozu) (*emptypb.Empty, error) {
	return nil, errors.New("rpc SaveMozu of service ConfigBuild is not implemented")
}

// ListMozu @alias=/ConfigBuild/ListMozu  查询模组信息
func (s *UnimplementedConfigBuild) ListMozu(ctx context.Context, req *ReqListMozu) (*RspListMozu, error) {
	return nil, errors.New("rpc ListMozu of service ConfigBuild is not implemented")
}

// DeleteMozu @alias=/ConfigBuild/DeleteMozu  删除模组信息
func (s *UnimplementedConfigBuild) DeleteMozu(ctx context.Context, req *ReqDeleteMozu) (*emptypb.Empty, error) {
	return nil, errors.New("rpc DeleteMozu of service ConfigBuild is not implemented")
}

// ImportModel @alias=/ConfigBuild/ImportModel  导入模组配置信息
func (s *UnimplementedConfigBuild) ImportModel(ctx context.Context, req *ReqImportModel) (*RspImportModel, error) {
	return nil, errors.New("rpc ImportModel of service ConfigBuild is not implemented")
}

type UnimplementedConfigQuery struct{}

// GetCollectorDevice @alias=/ConfigQuery/GetCollectorDevice   获取采集器下子设备
func (s *UnimplementedConfigQuery) GetCollectorDevice(ctx context.Context, req *ReqGetCollectorDevice) (*RspGetCollectorDevice, error) {
	return nil, errors.New("rpc GetCollectorDevice of service ConfigQuery is not implemented")
}

// GetCollectorPoint @alias=/ConfigQuery/GetCollectorPoint   获取采集器下的标准测点
func (s *UnimplementedConfigQuery) GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint) (*RspGetCollectorPoint, error) {
	return nil, errors.New("rpc GetCollectorPoint of service ConfigQuery is not implemented")
}

// GetCollectorTemplate @alias=/ConfigQuery/GetCollectorTemplate   获取采集模版配置信息
func (s *UnimplementedConfigQuery) GetCollectorTemplate(ctx context.Context, req *ReqGetCollectorTemplate) (*RspGetCollectorTemplate, error) {
	return nil, errors.New("rpc GetCollectorTemplate of service ConfigQuery is not implemented")
}

// GetConfigModifyTime @alias=/ConfigQuery/GetConfigModifyTime   获取配置更新时间
func (s *UnimplementedConfigQuery) GetConfigModifyTime(ctx context.Context, req *ReqGetCollectorDevice) (*RspGetConfigModifyTime, error) {
	return nil, errors.New("rpc GetConfigModifyTime of service ConfigQuery is not implemented")
}

// ExportCollectorConfig @alias=/ConfigQuery/ExportCollectorConfig   按模组导出所有的配置
func (s *UnimplementedConfigQuery) ExportCollectorConfig(ctx context.Context, req *ReqExportCollectorConfig) (*emptypb.Empty, error) {
	return nil, errors.New("rpc ExportCollectorConfig of service ConfigQuery is not implemented")
}

// ListCollectorDevice @alias=/ConfigQuery/ListCollectorDevice   获取采集器列表
func (s *UnimplementedConfigQuery) ListCollectorDevice(ctx context.Context, req *ReqListCollectorDevice) (*RspListCollectorDevice, error) {
	return nil, errors.New("rpc ListCollectorDevice of service ConfigQuery is not implemented")
}

// GetDeviceEntity @alias=/ConfigQuery/GetDeviceEntity   获取标准设备
func (s *UnimplementedConfigQuery) GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity) (*RspGetDeviceEntity, error) {
	return nil, errors.New("rpc GetDeviceEntity of service ConfigQuery is not implemented")
}

// GetDevicePoint @alias=/ConfigQuery/GetDevicePoint   获取标准测点
func (s *UnimplementedConfigQuery) GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint) (*RspGetDevicePoint, error) {
	return nil, errors.New("rpc GetDevicePoint of service ConfigQuery is not implemented")
}

// GetMozuInfo @alias=/ConfigQuery/GetMozuInfo   获取模组信息
func (s *UnimplementedConfigQuery) GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo) (*RspGetMozuInfo, error) {
	return nil, errors.New("rpc GetMozuInfo of service ConfigQuery is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ConfigBuildClientProxy defines service client proxy
type ConfigBuildClientProxy interface {
	// SaveMozu @alias=/ConfigBuild/SaveMozu   保存模组信息
	SaveMozu(ctx context.Context, req *ReqSaveMozu, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// ListMozu @alias=/ConfigBuild/ListMozu  查询模组信息
	ListMozu(ctx context.Context, req *ReqListMozu, opts ...client.Option) (rsp *RspListMozu, err error)
	// DeleteMozu @alias=/ConfigBuild/DeleteMozu  删除模组信息
	DeleteMozu(ctx context.Context, req *ReqDeleteMozu, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// ImportModel @alias=/ConfigBuild/ImportModel  导入模组配置信息
	ImportModel(ctx context.Context, req *ReqImportModel, opts ...client.Option) (rsp *RspImportModel, err error)
}

type ConfigBuildClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewConfigBuildClientProxy = func(opts ...client.Option) ConfigBuildClientProxy {
	return &ConfigBuildClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ConfigBuildClientProxyImpl) SaveMozu(ctx context.Context, req *ReqSaveMozu, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigBuild/SaveMozu")
	msg.WithCalleeServiceName(ConfigBuildServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigBuild")
	msg.WithCalleeMethod("SaveMozu")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigBuildClientProxyImpl) ListMozu(ctx context.Context, req *ReqListMozu, opts ...client.Option) (*RspListMozu, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigBuild/ListMozu")
	msg.WithCalleeServiceName(ConfigBuildServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigBuild")
	msg.WithCalleeMethod("ListMozu")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspListMozu{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigBuildClientProxyImpl) DeleteMozu(ctx context.Context, req *ReqDeleteMozu, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigBuild/DeleteMozu")
	msg.WithCalleeServiceName(ConfigBuildServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigBuild")
	msg.WithCalleeMethod("DeleteMozu")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigBuildClientProxyImpl) ImportModel(ctx context.Context, req *ReqImportModel, opts ...client.Option) (*RspImportModel, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigBuild/ImportModel")
	msg.WithCalleeServiceName(ConfigBuildServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigBuild")
	msg.WithCalleeMethod("ImportModel")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspImportModel{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// ConfigQueryClientProxy defines service client proxy
type ConfigQueryClientProxy interface {
	// GetCollectorDevice @alias=/ConfigQuery/GetCollectorDevice   获取采集器下子设备
	GetCollectorDevice(ctx context.Context, req *ReqGetCollectorDevice, opts ...client.Option) (rsp *RspGetCollectorDevice, err error)
	// GetCollectorPoint @alias=/ConfigQuery/GetCollectorPoint   获取采集器下的标准测点
	GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint, opts ...client.Option) (rsp *RspGetCollectorPoint, err error)
	// GetCollectorTemplate @alias=/ConfigQuery/GetCollectorTemplate   获取采集模版配置信息
	GetCollectorTemplate(ctx context.Context, req *ReqGetCollectorTemplate, opts ...client.Option) (rsp *RspGetCollectorTemplate, err error)
	// GetConfigModifyTime @alias=/ConfigQuery/GetConfigModifyTime   获取配置更新时间
	GetConfigModifyTime(ctx context.Context, req *ReqGetCollectorDevice, opts ...client.Option) (rsp *RspGetConfigModifyTime, err error)
	// ExportCollectorConfig @alias=/ConfigQuery/ExportCollectorConfig   按模组导出所有的配置
	ExportCollectorConfig(ctx context.Context, req *ReqExportCollectorConfig, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// ListCollectorDevice @alias=/ConfigQuery/ListCollectorDevice   获取采集器列表
	ListCollectorDevice(ctx context.Context, req *ReqListCollectorDevice, opts ...client.Option) (rsp *RspListCollectorDevice, err error)
	// GetDeviceEntity @alias=/ConfigQuery/GetDeviceEntity   获取标准设备
	GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity, opts ...client.Option) (rsp *RspGetDeviceEntity, err error)
	// GetDevicePoint @alias=/ConfigQuery/GetDevicePoint   获取标准测点
	GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint, opts ...client.Option) (rsp *RspGetDevicePoint, err error)
	// GetMozuInfo @alias=/ConfigQuery/GetMozuInfo   获取模组信息
	GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo, opts ...client.Option) (rsp *RspGetMozuInfo, err error)
}

type ConfigQueryClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewConfigQueryClientProxy = func(opts ...client.Option) ConfigQueryClientProxy {
	return &ConfigQueryClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ConfigQueryClientProxyImpl) GetCollectorDevice(ctx context.Context, req *ReqGetCollectorDevice, opts ...client.Option) (*RspGetCollectorDevice, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/GetCollectorDevice")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("GetCollectorDevice")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetCollectorDevice{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint, opts ...client.Option) (*RspGetCollectorPoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/GetCollectorPoint")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("GetCollectorPoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetCollectorPoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) GetCollectorTemplate(ctx context.Context, req *ReqGetCollectorTemplate, opts ...client.Option) (*RspGetCollectorTemplate, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/GetCollectorTemplate")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("GetCollectorTemplate")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetCollectorTemplate{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) GetConfigModifyTime(ctx context.Context, req *ReqGetCollectorDevice, opts ...client.Option) (*RspGetConfigModifyTime, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/GetConfigModifyTime")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("GetConfigModifyTime")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetConfigModifyTime{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) ExportCollectorConfig(ctx context.Context, req *ReqExportCollectorConfig, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/ExportCollectorConfig")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("ExportCollectorConfig")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) ListCollectorDevice(ctx context.Context, req *ReqListCollectorDevice, opts ...client.Option) (*RspListCollectorDevice, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/ListCollectorDevice")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("ListCollectorDevice")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspListCollectorDevice{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity, opts ...client.Option) (*RspGetDeviceEntity, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/GetDeviceEntity")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("GetDeviceEntity")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetDeviceEntity{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint, opts ...client.Option) (*RspGetDevicePoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/GetDevicePoint")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("GetDevicePoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetDevicePoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConfigQueryClientProxyImpl) GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo, opts ...client.Option) (*RspGetMozuInfo, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigQuery/GetMozuInfo")
	msg.WithCalleeServiceName(ConfigQueryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigQuery")
	msg.WithCalleeMethod("GetMozuInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetMozuInfo{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
