// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/data-compute/data-compute.proto

package data_compute

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ComputeService defines service.
type ComputeService interface {
	// ReceiveTask @alias=/Compute/ReceiveTask  接收标准点计算任务
	ReceiveTask(ctx context.Context, req *ReqReceiveTask) (*emptypb.Empty, error)
	// ShowTask @alias=/Compute/ShowTask  接收标准点计算任务
	ShowTask(ctx context.Context, req *ReqQueryFilter) (*RspShowTask, error)
	// ShowData @alias=/Compute/ShowData  接收标准点计算任务
	ShowData(ctx context.Context, req *ReqQueryFilter) (*RspShowData, error)
}

func ComputeService_ReceiveTask_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqReceiveTask{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ComputeService).ReceiveTask(ctx, reqbody.(*ReqReceiveTask))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ComputeService_ShowTask_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqQueryFilter{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ComputeService).ShowTask(ctx, reqbody.(*ReqQueryFilter))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ComputeService_ShowData_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqQueryFilter{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ComputeService).ShowData(ctx, reqbody.(*ReqQueryFilter))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ComputeServer_ServiceDesc descriptor for server.RegisterService.
var ComputeServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.data.compute.Compute",
	HandlerType: ((*ComputeService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Compute/ReceiveTask",
			Func: ComputeService_ReceiveTask_Handler,
		},
		{
			Name: "/Compute/ShowTask",
			Func: ComputeService_ShowTask_Handler,
		},
		{
			Name: "/Compute/ShowData",
			Func: ComputeService_ShowData_Handler,
		},
		{
			Name: "/tbos.data.compute.Compute/ReceiveTask",
			Func: ComputeService_ReceiveTask_Handler,
		},
		{
			Name: "/tbos.data.compute.Compute/ShowTask",
			Func: ComputeService_ShowTask_Handler,
		},
		{
			Name: "/tbos.data.compute.Compute/ShowData",
			Func: ComputeService_ShowData_Handler,
		},
	},
}

// RegisterComputeService registers service.
func RegisterComputeService(s server.Service, svr ComputeService) {
	if err := s.Register(&ComputeServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Compute register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedCompute struct{}

// ReceiveTask @alias=/Compute/ReceiveTask  接收标准点计算任务
func (s *UnimplementedCompute) ReceiveTask(ctx context.Context, req *ReqReceiveTask) (*emptypb.Empty, error) {
	return nil, errors.New("rpc ReceiveTask of service Compute is not implemented")
}

// ShowTask @alias=/Compute/ShowTask  接收标准点计算任务
func (s *UnimplementedCompute) ShowTask(ctx context.Context, req *ReqQueryFilter) (*RspShowTask, error) {
	return nil, errors.New("rpc ShowTask of service Compute is not implemented")
}

// ShowData @alias=/Compute/ShowData  接收标准点计算任务
func (s *UnimplementedCompute) ShowData(ctx context.Context, req *ReqQueryFilter) (*RspShowData, error) {
	return nil, errors.New("rpc ShowData of service Compute is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ComputeClientProxy defines service client proxy
type ComputeClientProxy interface {
	// ReceiveTask @alias=/Compute/ReceiveTask  接收标准点计算任务
	ReceiveTask(ctx context.Context, req *ReqReceiveTask, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// ShowTask @alias=/Compute/ShowTask  接收标准点计算任务
	ShowTask(ctx context.Context, req *ReqQueryFilter, opts ...client.Option) (rsp *RspShowTask, err error)
	// ShowData @alias=/Compute/ShowData  接收标准点计算任务
	ShowData(ctx context.Context, req *ReqQueryFilter, opts ...client.Option) (rsp *RspShowData, err error)
}

type ComputeClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewComputeClientProxy = func(opts ...client.Option) ComputeClientProxy {
	return &ComputeClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ComputeClientProxyImpl) ReceiveTask(ctx context.Context, req *ReqReceiveTask, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Compute/ReceiveTask")
	msg.WithCalleeServiceName(ComputeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Compute")
	msg.WithCalleeMethod("ReceiveTask")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ComputeClientProxyImpl) ShowTask(ctx context.Context, req *ReqQueryFilter, opts ...client.Option) (*RspShowTask, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Compute/ShowTask")
	msg.WithCalleeServiceName(ComputeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Compute")
	msg.WithCalleeMethod("ShowTask")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspShowTask{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ComputeClientProxyImpl) ShowData(ctx context.Context, req *ReqQueryFilter, opts ...client.Option) (*RspShowData, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Compute/ShowData")
	msg.WithCalleeServiceName(ComputeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Compute")
	msg.WithCalleeMethod("ShowData")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspShowData{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
