// Package gormutil provides ...
// @author: xincili
// -------------------------------------------
package gormutil

import (
	"time"
)

// Model a basic GoLang struct which includes the following fields: ID, CreatedAt, UpdatedAt
// It may be embedded into your model or you may build your own model without it
//
//	type User struct {
//	  gormutil.Model
//	}
type Model struct {

	// ID is the unique in time and space value for this object. It is typically generated by
	// the storage on successful creation of a resource and is not allowed to change on PUT
	// operations.
	//
	// Populated by the system.
	// Read-only.
	ID uint `gorm:"primarykey"`

	// CreatedAt is a timestamp representing the server time when this object was
	// created. It is not guaranteed to be set in happens-before order across separate operations.
	// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
	//
	// Populated by the system.
	// Read-only.
	// Null for lists.
	CreatedAt time.Time

	// UpdatedAt is a timestamp representing the server time when this object was updated.
	// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
	//
	// Populated by the system.
	// Read-only.
	// Null for lists.
	UpdatedAt time.Time
}
