// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/alarm-manage/alarm-manage.proto

package alarm_manage

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ManageService defines service.
type ManageService interface {
	// Bot @alias=/alarm/manage/bot 企微机器人回调
	Bot(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error)
	// PushAlarm @alias=/alarm/manage/pushAlarm 接口传输告警信息
	PushAlarm(ctx context.Context, req *AlarmMsgPb) (*emptypb.Empty, error)
	// ResendAlarm @alias=/alarm/manage/ResendAlarm 重新推送告警信息
	ResendAlarm(ctx context.Context, req *ReqResendAlarm) (*emptypb.Empty, error)
}

func ManageService_Bot_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &emptypb.Empty{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ManageService).Bot(ctx, reqbody.(*emptypb.Empty))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ManageService_PushAlarm_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AlarmMsgPb{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ManageService).PushAlarm(ctx, reqbody.(*AlarmMsgPb))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ManageService_ResendAlarm_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqResendAlarm{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ManageService).ResendAlarm(ctx, reqbody.(*ReqResendAlarm))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ManageServer_ServiceDesc descriptor for server.RegisterService.
var ManageServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.alarm.Manage",
	HandlerType: ((*ManageService)(nil)),
	Methods: []server.Method{
		{
			Name: "/alarm/manage/bot",
			Func: ManageService_Bot_Handler,
		},
		{
			Name: "/alarm/manage/pushAlarm",
			Func: ManageService_PushAlarm_Handler,
		},
		{
			Name: "/alarm/manage/ResendAlarm",
			Func: ManageService_ResendAlarm_Handler,
		},
		{
			Name: "/tbos.alarm.Manage/Bot",
			Func: ManageService_Bot_Handler,
		},
		{
			Name: "/tbos.alarm.Manage/PushAlarm",
			Func: ManageService_PushAlarm_Handler,
		},
		{
			Name: "/tbos.alarm.Manage/ResendAlarm",
			Func: ManageService_ResendAlarm_Handler,
		},
	},
}

// RegisterManageService registers service.
func RegisterManageService(s server.Service, svr ManageService) {
	if err := s.Register(&ManageServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Manage register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedManage struct{}

// Bot @alias=/alarm/manage/bot 企微机器人回调
func (s *UnimplementedManage) Bot(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, errors.New("rpc Bot of service Manage is not implemented")
}

// PushAlarm @alias=/alarm/manage/pushAlarm 接口传输告警信息
func (s *UnimplementedManage) PushAlarm(ctx context.Context, req *AlarmMsgPb) (*emptypb.Empty, error) {
	return nil, errors.New("rpc PushAlarm of service Manage is not implemented")
}

// ResendAlarm @alias=/alarm/manage/ResendAlarm 重新推送告警信息
func (s *UnimplementedManage) ResendAlarm(ctx context.Context, req *ReqResendAlarm) (*emptypb.Empty, error) {
	return nil, errors.New("rpc ResendAlarm of service Manage is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ManageClientProxy defines service client proxy
type ManageClientProxy interface {
	// Bot @alias=/alarm/manage/bot 企微机器人回调
	Bot(ctx context.Context, req *emptypb.Empty, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// PushAlarm @alias=/alarm/manage/pushAlarm 接口传输告警信息
	PushAlarm(ctx context.Context, req *AlarmMsgPb, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// ResendAlarm @alias=/alarm/manage/ResendAlarm 重新推送告警信息
	ResendAlarm(ctx context.Context, req *ReqResendAlarm, opts ...client.Option) (rsp *emptypb.Empty, err error)
}

type ManageClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewManageClientProxy = func(opts ...client.Option) ManageClientProxy {
	return &ManageClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ManageClientProxyImpl) Bot(ctx context.Context, req *emptypb.Empty, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/manage/bot")
	msg.WithCalleeServiceName(ManageServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Manage")
	msg.WithCalleeMethod("Bot")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ManageClientProxyImpl) PushAlarm(ctx context.Context, req *AlarmMsgPb, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/manage/pushAlarm")
	msg.WithCalleeServiceName(ManageServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Manage")
	msg.WithCalleeMethod("PushAlarm")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ManageClientProxyImpl) ResendAlarm(ctx context.Context, req *ReqResendAlarm, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/manage/ResendAlarm")
	msg.WithCalleeServiceName(ManageServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Manage")
	msg.WithCalleeMethod("ResendAlarm")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
