// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: collector.proto

package collector

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// DataBusService defines service.
type DataBusService interface {
	// Send @alias=/DataBus/Send
	Send(ctx context.Context, req *ReqSend) (*emptypb.Empty, error)
}

func DataBusService_Send_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqSend{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataBusService).Send(ctx, reqbody.(*ReqSend))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// DataBusServer_ServiceDesc descriptor for server.RegisterService.
var DataBusServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.collector.DataBus",
	HandlerType: ((*DataBusService)(nil)),
	Methods: []server.Method{
		{
			Name: "/DataBus/Send",
			Func: DataBusService_Send_Handler,
		},
		{
			Name: "/tbos.collector.DataBus/Send",
			Func: DataBusService_Send_Handler,
		},
	},
}

// RegisterDataBusService registers service.
func RegisterDataBusService(s server.Service, svr DataBusService) {
	if err := s.Register(&DataBusServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("DataBus register error:%v", err))
	}
}

// CollectPointForwardService defines service.
type CollectPointForwardService interface {
	// Forward @alias=/CollectPoint/Forward
	Forward(ctx context.Context, req *ReqSend) (*emptypb.Empty, error)
}

func CollectPointForwardService_Forward_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqSend{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectPointForwardService).Forward(ctx, reqbody.(*ReqSend))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// CollectPointForwardServer_ServiceDesc descriptor for server.RegisterService.
var CollectPointForwardServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.collector.CollectPointForward",
	HandlerType: ((*CollectPointForwardService)(nil)),
	Methods: []server.Method{
		{
			Name: "/CollectPoint/Forward",
			Func: CollectPointForwardService_Forward_Handler,
		},
		{
			Name: "/tbos.collector.CollectPointForward/Forward",
			Func: CollectPointForwardService_Forward_Handler,
		},
	},
}

// RegisterCollectPointForwardService registers service.
func RegisterCollectPointForwardService(s server.Service, svr CollectPointForwardService) {
	if err := s.Register(&CollectPointForwardServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("CollectPointForward register error:%v", err))
	}
}

// ConfigBusService defines service.
type ConfigBusService interface {
	// FetchConfig @alias=/ConfigBus/FetchConfig
	FetchConfig(ctx context.Context, req *ReqFetchConfig) (*RspFetchConfig, error)
}

func ConfigBusService_FetchConfig_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqFetchConfig{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConfigBusService).FetchConfig(ctx, reqbody.(*ReqFetchConfig))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ConfigBusServer_ServiceDesc descriptor for server.RegisterService.
var ConfigBusServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.collector.ConfigBus",
	HandlerType: ((*ConfigBusService)(nil)),
	Methods: []server.Method{
		{
			Name: "/ConfigBus/FetchConfig",
			Func: ConfigBusService_FetchConfig_Handler,
		},
		{
			Name: "/tbos.collector.ConfigBus/FetchConfig",
			Func: ConfigBusService_FetchConfig_Handler,
		},
	},
}

// RegisterConfigBusService registers service.
func RegisterConfigBusService(s server.Service, svr ConfigBusService) {
	if err := s.Register(&ConfigBusServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ConfigBus register error:%v", err))
	}
}

// ExternalPlatformService defines service.
type ExternalPlatformService interface {
	// Data @alias=/external-platform/data
	Data(ctx context.Context, req *ExternalData) (*emptypb.Empty, error)
}

func ExternalPlatformService_Data_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ExternalData{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ExternalPlatformService).Data(ctx, reqbody.(*ExternalData))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ExternalPlatformServer_ServiceDesc descriptor for server.RegisterService.
var ExternalPlatformServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.collector.ExternalPlatform",
	HandlerType: ((*ExternalPlatformService)(nil)),
	Methods: []server.Method{
		{
			Name: "/external-platform/data",
			Func: ExternalPlatformService_Data_Handler,
		},
		{
			Name: "/tbos.collector.ExternalPlatform/Data",
			Func: ExternalPlatformService_Data_Handler,
		},
	},
}

// RegisterExternalPlatformService registers service.
func RegisterExternalPlatformService(s server.Service, svr ExternalPlatformService) {
	if err := s.Register(&ExternalPlatformServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ExternalPlatform register error:%v", err))
	}
}

// SpotConfigService defines service.
type SpotConfigService interface {
	// ReportElvdb @alias=/spot/ReportElvdb
	ReportElvdb(ctx context.Context, req *ReportElvdbReq) (*emptypb.Empty, error)
	// GetBAConfs @alias=/spot/GetBAConfs
	GetBAConfs(ctx context.Context, req *GetBAConfsReq) (*GetBAConfsRsp, error)
}

func SpotConfigService_ReportElvdb_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReportElvdbReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SpotConfigService).ReportElvdb(ctx, reqbody.(*ReportElvdbReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SpotConfigService_GetBAConfs_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetBAConfsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SpotConfigService).GetBAConfs(ctx, reqbody.(*GetBAConfsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// SpotConfigServer_ServiceDesc descriptor for server.RegisterService.
var SpotConfigServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.collector.SpotConfig",
	HandlerType: ((*SpotConfigService)(nil)),
	Methods: []server.Method{
		{
			Name: "/spot/ReportElvdb",
			Func: SpotConfigService_ReportElvdb_Handler,
		},
		{
			Name: "/spot/GetBAConfs",
			Func: SpotConfigService_GetBAConfs_Handler,
		},
		{
			Name: "/tbos.collector.SpotConfig/ReportElvdb",
			Func: SpotConfigService_ReportElvdb_Handler,
		},
		{
			Name: "/tbos.collector.SpotConfig/GetBAConfs",
			Func: SpotConfigService_GetBAConfs_Handler,
		},
	},
}

// RegisterSpotConfigService registers service.
func RegisterSpotConfigService(s server.Service, svr SpotConfigService) {
	if err := s.Register(&SpotConfigServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("SpotConfig register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedDataBus struct{}

// Send @alias=/DataBus/Send
func (s *UnimplementedDataBus) Send(ctx context.Context, req *ReqSend) (*emptypb.Empty, error) {
	return nil, errors.New("rpc Send of service DataBus is not implemented")
}

type UnimplementedCollectPointForward struct{}

// Forward @alias=/CollectPoint/Forward
func (s *UnimplementedCollectPointForward) Forward(ctx context.Context, req *ReqSend) (*emptypb.Empty, error) {
	return nil, errors.New("rpc Forward of service CollectPointForward is not implemented")
}

type UnimplementedConfigBus struct{}

// FetchConfig @alias=/ConfigBus/FetchConfig
func (s *UnimplementedConfigBus) FetchConfig(ctx context.Context, req *ReqFetchConfig) (*RspFetchConfig, error) {
	return nil, errors.New("rpc FetchConfig of service ConfigBus is not implemented")
}

type UnimplementedExternalPlatform struct{}

// Data @alias=/external-platform/data
func (s *UnimplementedExternalPlatform) Data(ctx context.Context, req *ExternalData) (*emptypb.Empty, error) {
	return nil, errors.New("rpc Data of service ExternalPlatform is not implemented")
}

type UnimplementedSpotConfig struct{}

// ReportElvdb @alias=/spot/ReportElvdb
func (s *UnimplementedSpotConfig) ReportElvdb(ctx context.Context, req *ReportElvdbReq) (*emptypb.Empty, error) {
	return nil, errors.New("rpc ReportElvdb of service SpotConfig is not implemented")
}

// GetBAConfs @alias=/spot/GetBAConfs
func (s *UnimplementedSpotConfig) GetBAConfs(ctx context.Context, req *GetBAConfsReq) (*GetBAConfsRsp, error) {
	return nil, errors.New("rpc GetBAConfs of service SpotConfig is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// DataBusClientProxy defines service client proxy
type DataBusClientProxy interface {
	// Send @alias=/DataBus/Send
	Send(ctx context.Context, req *ReqSend, opts ...client.Option) (rsp *emptypb.Empty, err error)
}

type DataBusClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewDataBusClientProxy = func(opts ...client.Option) DataBusClientProxy {
	return &DataBusClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *DataBusClientProxyImpl) Send(ctx context.Context, req *ReqSend, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/DataBus/Send")
	msg.WithCalleeServiceName(DataBusServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("DataBus")
	msg.WithCalleeMethod("Send")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// CollectPointForwardClientProxy defines service client proxy
type CollectPointForwardClientProxy interface {
	// Forward @alias=/CollectPoint/Forward
	Forward(ctx context.Context, req *ReqSend, opts ...client.Option) (rsp *emptypb.Empty, err error)
}

type CollectPointForwardClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewCollectPointForwardClientProxy = func(opts ...client.Option) CollectPointForwardClientProxy {
	return &CollectPointForwardClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *CollectPointForwardClientProxyImpl) Forward(ctx context.Context, req *ReqSend, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/CollectPoint/Forward")
	msg.WithCalleeServiceName(CollectPointForwardServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("CollectPointForward")
	msg.WithCalleeMethod("Forward")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// ConfigBusClientProxy defines service client proxy
type ConfigBusClientProxy interface {
	// FetchConfig @alias=/ConfigBus/FetchConfig
	FetchConfig(ctx context.Context, req *ReqFetchConfig, opts ...client.Option) (rsp *RspFetchConfig, err error)
}

type ConfigBusClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewConfigBusClientProxy = func(opts ...client.Option) ConfigBusClientProxy {
	return &ConfigBusClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ConfigBusClientProxyImpl) FetchConfig(ctx context.Context, req *ReqFetchConfig, opts ...client.Option) (*RspFetchConfig, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/ConfigBus/FetchConfig")
	msg.WithCalleeServiceName(ConfigBusServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConfigBus")
	msg.WithCalleeMethod("FetchConfig")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspFetchConfig{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// ExternalPlatformClientProxy defines service client proxy
type ExternalPlatformClientProxy interface {
	// Data @alias=/external-platform/data
	Data(ctx context.Context, req *ExternalData, opts ...client.Option) (rsp *emptypb.Empty, err error)
}

type ExternalPlatformClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewExternalPlatformClientProxy = func(opts ...client.Option) ExternalPlatformClientProxy {
	return &ExternalPlatformClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ExternalPlatformClientProxyImpl) Data(ctx context.Context, req *ExternalData, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/external-platform/data")
	msg.WithCalleeServiceName(ExternalPlatformServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ExternalPlatform")
	msg.WithCalleeMethod("Data")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// SpotConfigClientProxy defines service client proxy
type SpotConfigClientProxy interface {
	// ReportElvdb @alias=/spot/ReportElvdb
	ReportElvdb(ctx context.Context, req *ReportElvdbReq, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// GetBAConfs @alias=/spot/GetBAConfs
	GetBAConfs(ctx context.Context, req *GetBAConfsReq, opts ...client.Option) (rsp *GetBAConfsRsp, err error)
}

type SpotConfigClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewSpotConfigClientProxy = func(opts ...client.Option) SpotConfigClientProxy {
	return &SpotConfigClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *SpotConfigClientProxyImpl) ReportElvdb(ctx context.Context, req *ReportElvdbReq, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/spot/ReportElvdb")
	msg.WithCalleeServiceName(SpotConfigServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SpotConfig")
	msg.WithCalleeMethod("ReportElvdb")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SpotConfigClientProxyImpl) GetBAConfs(ctx context.Context, req *GetBAConfsReq, opts ...client.Option) (*GetBAConfsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/spot/GetBAConfs")
	msg.WithCalleeServiceName(SpotConfigServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SpotConfig")
	msg.WithCalleeMethod("GetBAConfs")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetBAConfsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
