// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.1
// source: collector.proto

package collector

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReqFetchConfig_FetchType int32

const (
	ReqFetchConfig_INVALID                   ReqFetchConfig_FetchType = 0
	ReqFetchConfig_FETCH_COLLECTOR_DEVICES   ReqFetchConfig_FetchType = 1
	ReqFetchConfig_FETCH_COLLECTOR_TEMPLATES ReqFetchConfig_FetchType = 2
	ReqFetchConfig_FETCH_STD_POINTS          ReqFetchConfig_FetchType = 3
	ReqFetchConfig_FETCH_CONFIG_MODIFY_TIME  ReqFetchConfig_FetchType = 4
	ReqFetchConfig_FETCH_STD_DEVICES         ReqFetchConfig_FetchType = 5
	ReqFetchConfig_FETCH_COLLECTOR_POINTS    ReqFetchConfig_FetchType = 6
)

// Enum value maps for ReqFetchConfig_FetchType.
var (
	ReqFetchConfig_FetchType_name = map[int32]string{
		0: "INVALID",
		1: "FETCH_COLLECTOR_DEVICES",
		2: "FETCH_COLLECTOR_TEMPLATES",
		3: "FETCH_STD_POINTS",
		4: "FETCH_CONFIG_MODIFY_TIME",
		5: "FETCH_STD_DEVICES",
		6: "FETCH_COLLECTOR_POINTS",
	}
	ReqFetchConfig_FetchType_value = map[string]int32{
		"INVALID":                   0,
		"FETCH_COLLECTOR_DEVICES":   1,
		"FETCH_COLLECTOR_TEMPLATES": 2,
		"FETCH_STD_POINTS":          3,
		"FETCH_CONFIG_MODIFY_TIME":  4,
		"FETCH_STD_DEVICES":         5,
		"FETCH_COLLECTOR_POINTS":    6,
	}
)

func (x ReqFetchConfig_FetchType) Enum() *ReqFetchConfig_FetchType {
	p := new(ReqFetchConfig_FetchType)
	*p = x
	return p
}

func (x ReqFetchConfig_FetchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqFetchConfig_FetchType) Descriptor() protoreflect.EnumDescriptor {
	return file_collector_proto_enumTypes[0].Descriptor()
}

func (ReqFetchConfig_FetchType) Type() protoreflect.EnumType {
	return &file_collector_proto_enumTypes[0]
}

func (x ReqFetchConfig_FetchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqFetchConfig_FetchType.Descriptor instead.
func (ReqFetchConfig_FetchType) EnumDescriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{1, 0}
}

type ReqFetchConfig_FetchKey int32

const (
	ReqFetchConfig_DEVICE_NUMBER ReqFetchConfig_FetchKey = 0
	ReqFetchConfig_DEVICE_SN     ReqFetchConfig_FetchKey = 1
)

// Enum value maps for ReqFetchConfig_FetchKey.
var (
	ReqFetchConfig_FetchKey_name = map[int32]string{
		0: "DEVICE_NUMBER",
		1: "DEVICE_SN",
	}
	ReqFetchConfig_FetchKey_value = map[string]int32{
		"DEVICE_NUMBER": 0,
		"DEVICE_SN":     1,
	}
)

func (x ReqFetchConfig_FetchKey) Enum() *ReqFetchConfig_FetchKey {
	p := new(ReqFetchConfig_FetchKey)
	*p = x
	return p
}

func (x ReqFetchConfig_FetchKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqFetchConfig_FetchKey) Descriptor() protoreflect.EnumDescriptor {
	return file_collector_proto_enumTypes[1].Descriptor()
}

func (ReqFetchConfig_FetchKey) Type() protoreflect.EnumType {
	return &file_collector_proto_enumTypes[1]
}

func (x ReqFetchConfig_FetchKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqFetchConfig_FetchKey.Descriptor instead.
func (ReqFetchConfig_FetchKey) EnumDescriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{1, 1}
}

// 采集器上传数据请求体
type ReqSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSend) Reset() {
	*x = ReqSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSend) ProtoMessage() {}

func (x *ReqSend) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSend.ProtoReflect.Descriptor instead.
func (*ReqSend) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSend) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReqSend) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// 配置获取请求体
type ReqFetchConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FetchType ReqFetchConfig_FetchType `protobuf:"varint,1,opt,name=fetch_type,json=fetchType,proto3,enum=tbos.collector.ReqFetchConfig_FetchType" json:"fetch_type,omitempty"`
	Params    []byte                   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	FetchKey  ReqFetchConfig_FetchKey  `protobuf:"varint,3,opt,name=fetch_key,json=fetchKey,proto3,enum=tbos.collector.ReqFetchConfig_FetchKey" json:"fetch_key,omitempty"`
}

func (x *ReqFetchConfig) Reset() {
	*x = ReqFetchConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqFetchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFetchConfig) ProtoMessage() {}

func (x *ReqFetchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFetchConfig.ProtoReflect.Descriptor instead.
func (*ReqFetchConfig) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{1}
}

func (x *ReqFetchConfig) GetFetchType() ReqFetchConfig_FetchType {
	if x != nil {
		return x.FetchType
	}
	return ReqFetchConfig_INVALID
}

func (x *ReqFetchConfig) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ReqFetchConfig) GetFetchKey() ReqFetchConfig_FetchKey {
	if x != nil {
		return x.FetchKey
	}
	return ReqFetchConfig_DEVICE_NUMBER
}

// 配置获取响应体
type RspFetchConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RspFetchConfig) Reset() {
	*x = RspFetchConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspFetchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspFetchConfig) ProtoMessage() {}

func (x *RspFetchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspFetchConfig.ProtoReflect.Descriptor instead.
func (*RspFetchConfig) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{2}
}

func (x *RspFetchConfig) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExternalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformId string                `protobuf:"bytes,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"` // 外部云平台的ID标识
	Seq        uint64                `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                // 消息序列号
	CollectS   int64                 `protobuf:"varint,3,opt,name=collect_s,json=collectS,proto3" json:"collect_s,omitempty"`      // 采集数据时的时间戳（秒）
	PushMs     int64                 `protobuf:"varint,4,opt,name=push_ms,json=pushMs,proto3" json:"push_ms,omitempty"`            // 推送数据时的时间戳（毫秒）
	Interval   int32                 `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`                      // 上报周期
	MozuId     int32                 `protobuf:"varint,6,opt,name=mozu_id,json=mozuId,proto3" json:"mozu_id,omitempty"`            // 模组id
	Points     []*ExternalData_Point `protobuf:"bytes,7,rep,name=points,proto3" json:"points,omitempty"`                           // 测点数据集合
}

func (x *ExternalData) Reset() {
	*x = ExternalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalData) ProtoMessage() {}

func (x *ExternalData) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalData.ProtoReflect.Descriptor instead.
func (*ExternalData) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{3}
}

func (x *ExternalData) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *ExternalData) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ExternalData) GetCollectS() int64 {
	if x != nil {
		return x.CollectS
	}
	return 0
}

func (x *ExternalData) GetPushMs() int64 {
	if x != nil {
		return x.PushMs
	}
	return 0
}

func (x *ExternalData) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *ExternalData) GetMozuId() int32 {
	if x != nil {
		return x.MozuId
	}
	return 0
}

func (x *ExternalData) GetPoints() []*ExternalData_Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type ReportElvdbReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MozuId int32 `protobuf:"varint,1,opt,name=mozu_id,json=mozuId,proto3" json:"mozu_id,omitempty"`
}

func (x *ReportElvdbReq) Reset() {
	*x = ReportElvdbReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportElvdbReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportElvdbReq) ProtoMessage() {}

func (x *ReportElvdbReq) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportElvdbReq.ProtoReflect.Descriptor instead.
func (*ReportElvdbReq) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{4}
}

func (x *ReportElvdbReq) GetMozuId() int32 {
	if x != nil {
		return x.MozuId
	}
	return 0
}

type GetBAConfsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBAConfsReq) Reset() {
	*x = GetBAConfsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBAConfsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBAConfsReq) ProtoMessage() {}

func (x *GetBAConfsReq) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBAConfsReq.ProtoReflect.Descriptor instead.
func (*GetBAConfsReq) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{5}
}

type GetBAConfsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*BAConfItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetBAConfsRsp) Reset() {
	*x = GetBAConfsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBAConfsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBAConfsRsp) ProtoMessage() {}

func (x *GetBAConfsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBAConfsRsp.ProtoReflect.Descriptor instead.
func (*GetBAConfsRsp) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{6}
}

func (x *GetBAConfsRsp) GetList() []*BAConfItem {
	if x != nil {
		return x.List
	}
	return nil
}

type BAConfItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MozuId   int32  `protobuf:"varint,1,opt,name=mozu_id,json=mozuId,proto3" json:"mozu_id,omitempty"`
	Addr     string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BAConfItem) Reset() {
	*x = BAConfItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAConfItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAConfItem) ProtoMessage() {}

func (x *BAConfItem) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAConfItem.ProtoReflect.Descriptor instead.
func (*BAConfItem) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{7}
}

func (x *BAConfItem) GetMozuId() int32 {
	if x != nil {
		return x.MozuId
	}
	return 0
}

func (x *BAConfItem) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BAConfItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BAConfItem) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ExternalData_Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I string `protobuf:"bytes,1,opt,name=i,proto3" json:"i,omitempty"` // 测点名称或id
	V string `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"` // 测点值
	Q string `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"` // 测点值的质量
	T string `protobuf:"bytes,4,opt,name=t,proto3" json:"t,omitempty"` // 测点值的时间戳（秒）
}

func (x *ExternalData_Point) Reset() {
	*x = ExternalData_Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalData_Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalData_Point) ProtoMessage() {}

func (x *ExternalData_Point) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalData_Point.ProtoReflect.Descriptor instead.
func (*ExternalData_Point) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ExternalData_Point) GetI() string {
	if x != nil {
		return x.I
	}
	return ""
}

func (x *ExternalData_Point) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *ExternalData_Point) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ExternalData_Point) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

var File_collector_proto protoreflect.FileDescriptor

var file_collector_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xa3, 0x03, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x47, 0x0a, 0x0a, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x09, 0x66, 0x65, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x44, 0x0a, 0x09, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4b, 0x65,
	0x79, 0x52, 0x08, 0x66, 0x65, 0x74, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x22, 0xbb, 0x01, 0x0a, 0x09,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f,
	0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45,
	0x53, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x4f, 0x4c,
	0x4c, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x53,
	0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x44, 0x5f,
	0x50, 0x4f, 0x49, 0x4e, 0x54, 0x53, 0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18, 0x46, 0x45, 0x54, 0x43,
	0x48, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x59, 0x5f,
	0x54, 0x49, 0x4d, 0x45, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f,
	0x53, 0x54, 0x44, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x53, 0x10, 0x05, 0x12, 0x1a, 0x0a,
	0x16, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x4f, 0x52,
	0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x53, 0x10, 0x06, 0x22, 0x2c, 0x0a, 0x08, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f,
	0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x53, 0x4e, 0x10, 0x01, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x73, 0x70, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa9, 0x02,
	0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x70, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x6f, 0x7a, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x6f, 0x7a, 0x75, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x06,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74,
	0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x3f, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x69, 0x12,
	0x0c, 0x0a, 0x01, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x0c, 0x0a,
	0x01, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x74, 0x22, 0x29, 0x0a, 0x0e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x45, 0x6c, 0x76, 0x64, 0x62, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6d,
	0x6f, 0x7a, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x6f,
	0x7a, 0x75, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x41, 0x43, 0x6f, 0x6e,
	0x66, 0x73, 0x52, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x41, 0x43, 0x6f,
	0x6e, 0x66, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x42, 0x41, 0x43, 0x6f, 0x6e, 0x66, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x71, 0x0a, 0x0a, 0x42, 0x41, 0x43, 0x6f, 0x6e, 0x66,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x6f, 0x7a, 0x75, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x6f, 0x7a, 0x75, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x42, 0x0a, 0x07, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x17, 0x2e, 0x74,
	0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x53, 0x65, 0x6e, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x51, 0x0a,
	0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12,
	0x17, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x32, 0x5a, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x75, 0x73, 0x12, 0x4d, 0x0a,
	0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x2e, 0x74,
	0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x1e, 0x2e, 0x74,
	0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x73,
	0x70, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x32, 0x50, 0x0a, 0x10,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x3c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x9f,
	0x01, 0x0a, 0x0a, 0x53, 0x70, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x45, 0x0a,
	0x0b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6c, 0x76, 0x64, 0x62, 0x12, 0x1e, 0x2e, 0x74,
	0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x45, 0x6c, 0x76, 0x64, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x41, 0x43, 0x6f, 0x6e,
	0x66, 0x73, 0x12, 0x1d, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x41, 0x43, 0x6f, 0x6e, 0x66, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x1d, 0x2e, 0x74, 0x62, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x41, 0x43, 0x6f, 0x6e, 0x66, 0x73, 0x52, 0x73, 0x70,
	0x42, 0x18, 0x5a, 0x16, 0x74, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_collector_proto_rawDescOnce sync.Once
	file_collector_proto_rawDescData = file_collector_proto_rawDesc
)

func file_collector_proto_rawDescGZIP() []byte {
	file_collector_proto_rawDescOnce.Do(func() {
		file_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_collector_proto_rawDescData)
	})
	return file_collector_proto_rawDescData
}

var file_collector_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_collector_proto_goTypes = []interface{}{
	(ReqFetchConfig_FetchType)(0), // 0: tbos.collector.ReqFetchConfig.FetchType
	(ReqFetchConfig_FetchKey)(0),  // 1: tbos.collector.ReqFetchConfig.FetchKey
	(*ReqSend)(nil),               // 2: tbos.collector.ReqSend
	(*ReqFetchConfig)(nil),        // 3: tbos.collector.ReqFetchConfig
	(*RspFetchConfig)(nil),        // 4: tbos.collector.RspFetchConfig
	(*ExternalData)(nil),          // 5: tbos.collector.ExternalData
	(*ReportElvdbReq)(nil),        // 6: tbos.collector.ReportElvdbReq
	(*GetBAConfsReq)(nil),         // 7: tbos.collector.GetBAConfsReq
	(*GetBAConfsRsp)(nil),         // 8: tbos.collector.GetBAConfsRsp
	(*BAConfItem)(nil),            // 9: tbos.collector.BAConfItem
	(*ExternalData_Point)(nil),    // 10: tbos.collector.ExternalData.Point
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_collector_proto_depIdxs = []int32{
	0,  // 0: tbos.collector.ReqFetchConfig.fetch_type:type_name -> tbos.collector.ReqFetchConfig.FetchType
	1,  // 1: tbos.collector.ReqFetchConfig.fetch_key:type_name -> tbos.collector.ReqFetchConfig.FetchKey
	10, // 2: tbos.collector.ExternalData.points:type_name -> tbos.collector.ExternalData.Point
	9,  // 3: tbos.collector.GetBAConfsRsp.list:type_name -> tbos.collector.BAConfItem
	2,  // 4: tbos.collector.DataBus.Send:input_type -> tbos.collector.ReqSend
	2,  // 5: tbos.collector.CollectPointForward.Forward:input_type -> tbos.collector.ReqSend
	3,  // 6: tbos.collector.ConfigBus.FetchConfig:input_type -> tbos.collector.ReqFetchConfig
	5,  // 7: tbos.collector.ExternalPlatform.Data:input_type -> tbos.collector.ExternalData
	6,  // 8: tbos.collector.SpotConfig.ReportElvdb:input_type -> tbos.collector.ReportElvdbReq
	7,  // 9: tbos.collector.SpotConfig.GetBAConfs:input_type -> tbos.collector.GetBAConfsReq
	11, // 10: tbos.collector.DataBus.Send:output_type -> google.protobuf.Empty
	11, // 11: tbos.collector.CollectPointForward.Forward:output_type -> google.protobuf.Empty
	4,  // 12: tbos.collector.ConfigBus.FetchConfig:output_type -> tbos.collector.RspFetchConfig
	11, // 13: tbos.collector.ExternalPlatform.Data:output_type -> google.protobuf.Empty
	11, // 14: tbos.collector.SpotConfig.ReportElvdb:output_type -> google.protobuf.Empty
	8,  // 15: tbos.collector.SpotConfig.GetBAConfs:output_type -> tbos.collector.GetBAConfsRsp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_collector_proto_init() }
func file_collector_proto_init() {
	if File_collector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqFetchConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspFetchConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportElvdbReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBAConfsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBAConfsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAConfItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalData_Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collector_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_collector_proto_goTypes,
		DependencyIndexes: file_collector_proto_depIdxs,
		EnumInfos:         file_collector_proto_enumTypes,
		MessageInfos:      file_collector_proto_msgTypes,
	}.Build()
	File_collector_proto = out.File
	file_collector_proto_rawDesc = nil
	file_collector_proto_goTypes = nil
	file_collector_proto_depIdxs = nil
}
