// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/scheduler/scheduler.proto

package scheduler

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// RegisterService defines service.
type RegisterService interface {
	// Heartbeat @alias=/Register/Heartbeat  上报心跳
	Heartbeat(ctx context.Context, req *WorkerInfo) (*emptypb.Empty, error)
}

func RegisterService_Heartbeat_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &WorkerInfo{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RegisterService).Heartbeat(ctx, reqbody.(*WorkerInfo))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// RegisterServer_ServiceDesc descriptor for server.RegisterService.
var RegisterServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.scheduler.Register",
	HandlerType: ((*RegisterService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Register/Heartbeat",
			Func: RegisterService_Heartbeat_Handler,
		},
		{
			Name: "/tbos.scheduler.Register/Heartbeat",
			Func: RegisterService_Heartbeat_Handler,
		},
	},
}

// RegisterRegisterService registers service.
func RegisterRegisterService(s server.Service, svr RegisterService) {
	if err := s.Register(&RegisterServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Register register error:%v", err))
	}
}

// AdminService defines service.
type AdminService interface {
	// ResetScheduler @alias=/Admin/ResetScheduler  重置调度任务
	ResetScheduler(ctx context.Context, req *ReqResetScheduler) (*emptypb.Empty, error)
	// ShowAllScheduler @alias=/Admin/ShowAllScheduler  展示所有调度任务
	ShowAllScheduler(ctx context.Context, req *emptypb.Empty) (*RspShowAllScheduler, error)
}

func AdminService_ResetScheduler_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqResetScheduler{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminService).ResetScheduler(ctx, reqbody.(*ReqResetScheduler))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminService_ShowAllScheduler_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &emptypb.Empty{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminService).ShowAllScheduler(ctx, reqbody.(*emptypb.Empty))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AdminServer_ServiceDesc descriptor for server.RegisterService.
var AdminServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.scheduler.Admin",
	HandlerType: ((*AdminService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Admin/ResetScheduler",
			Func: AdminService_ResetScheduler_Handler,
		},
		{
			Name: "/Admin/ShowAllScheduler",
			Func: AdminService_ShowAllScheduler_Handler,
		},
		{
			Name: "/tbos.scheduler.Admin/ResetScheduler",
			Func: AdminService_ResetScheduler_Handler,
		},
		{
			Name: "/tbos.scheduler.Admin/ShowAllScheduler",
			Func: AdminService_ShowAllScheduler_Handler,
		},
	},
}

// RegisterAdminService registers service.
func RegisterAdminService(s server.Service, svr AdminService) {
	if err := s.Register(&AdminServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Admin register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedRegister struct{}

// Heartbeat @alias=/Register/Heartbeat  上报心跳
func (s *UnimplementedRegister) Heartbeat(ctx context.Context, req *WorkerInfo) (*emptypb.Empty, error) {
	return nil, errors.New("rpc Heartbeat of service Register is not implemented")
}

type UnimplementedAdmin struct{}

// ResetScheduler @alias=/Admin/ResetScheduler  重置调度任务
func (s *UnimplementedAdmin) ResetScheduler(ctx context.Context, req *ReqResetScheduler) (*emptypb.Empty, error) {
	return nil, errors.New("rpc ResetScheduler of service Admin is not implemented")
}

// ShowAllScheduler @alias=/Admin/ShowAllScheduler  展示所有调度任务
func (s *UnimplementedAdmin) ShowAllScheduler(ctx context.Context, req *emptypb.Empty) (*RspShowAllScheduler, error) {
	return nil, errors.New("rpc ShowAllScheduler of service Admin is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// RegisterClientProxy defines service client proxy
type RegisterClientProxy interface {
	// Heartbeat @alias=/Register/Heartbeat  上报心跳
	Heartbeat(ctx context.Context, req *WorkerInfo, opts ...client.Option) (rsp *emptypb.Empty, err error)
}

type RegisterClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewRegisterClientProxy = func(opts ...client.Option) RegisterClientProxy {
	return &RegisterClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *RegisterClientProxyImpl) Heartbeat(ctx context.Context, req *WorkerInfo, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Register/Heartbeat")
	msg.WithCalleeServiceName(RegisterServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Register")
	msg.WithCalleeMethod("Heartbeat")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// AdminClientProxy defines service client proxy
type AdminClientProxy interface {
	// ResetScheduler @alias=/Admin/ResetScheduler  重置调度任务
	ResetScheduler(ctx context.Context, req *ReqResetScheduler, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// ShowAllScheduler @alias=/Admin/ShowAllScheduler  展示所有调度任务
	ShowAllScheduler(ctx context.Context, req *emptypb.Empty, opts ...client.Option) (rsp *RspShowAllScheduler, err error)
}

type AdminClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAdminClientProxy = func(opts ...client.Option) AdminClientProxy {
	return &AdminClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AdminClientProxyImpl) ResetScheduler(ctx context.Context, req *ReqResetScheduler, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Admin/ResetScheduler")
	msg.WithCalleeServiceName(AdminServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Admin")
	msg.WithCalleeMethod("ResetScheduler")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminClientProxyImpl) ShowAllScheduler(ctx context.Context, req *emptypb.Empty, opts ...client.Option) (*RspShowAllScheduler, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Admin/ShowAllScheduler")
	msg.WithCalleeServiceName(AdminServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Admin")
	msg.WithCalleeMethod("ShowAllScheduler")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspShowAllScheduler{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
