// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/data-query/data-query.proto

package data_query

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// DataService defines service.
type DataService interface {
	// DataQuery @alias=/data/query    DataQuery 数据查询接口
	DataQuery(ctx context.Context, req *QueryRequest) (*QueryResponse, error) // ------------------------------ query end ------------------------------
	// DataChange @alias=/data/change    DataChange  数据变化查询接口
	DataChange(ctx context.Context, req *ChangeRequest) (*ChangeResponse, error)
	// DataPointChange @alias=/data/pointChange    DataPointChange  变化测点查询接口
	DataPointChange(ctx context.Context, req *PointChangeRequest) (*PointChangeResponse, error) // ------------------------------ change end ------------------------------
}

func DataService_DataQuery_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataService).DataQuery(ctx, reqbody.(*QueryRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataService_DataChange_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ChangeRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataService).DataChange(ctx, reqbody.(*ChangeRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataService_DataPointChange_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PointChangeRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataService).DataPointChange(ctx, reqbody.(*PointChangeRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// DataServer_ServiceDesc descriptor for server.RegisterService.
var DataServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.data.query.Data",
	HandlerType: ((*DataService)(nil)),
	Methods: []server.Method{
		{
			Name: "/data/query",
			Func: DataService_DataQuery_Handler,
		},
		{
			Name: "/data/change",
			Func: DataService_DataChange_Handler,
		},
		{
			Name: "/data/pointChange",
			Func: DataService_DataPointChange_Handler,
		},
		{
			Name: "/tbos.data.query.Data/DataQuery",
			Func: DataService_DataQuery_Handler,
		},
		{
			Name: "/tbos.data.query.Data/DataChange",
			Func: DataService_DataChange_Handler,
		},
		{
			Name: "/tbos.data.query.Data/DataPointChange",
			Func: DataService_DataPointChange_Handler,
		},
	},
}

// RegisterDataService registers service.
func RegisterDataService(s server.Service, svr DataService) {
	if err := s.Register(&DataServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Data register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedData struct{}

// DataQuery @alias=/data/query    DataQuery 数据查询接口
func (s *UnimplementedData) DataQuery(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, errors.New("rpc DataQuery of service Data is not implemented")
}

// DataChange @alias=/data/change    DataChange  数据变化查询接口
func (s *UnimplementedData) DataChange(ctx context.Context, req *ChangeRequest) (*ChangeResponse, error) {
	return nil, errors.New("rpc DataChange of service Data is not implemented")
}

// DataPointChange @alias=/data/pointChange    DataPointChange  变化测点查询接口
func (s *UnimplementedData) DataPointChange(ctx context.Context, req *PointChangeRequest) (*PointChangeResponse, error) {
	return nil, errors.New("rpc DataPointChange of service Data is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// DataClientProxy defines service client proxy
type DataClientProxy interface {
	// DataQuery @alias=/data/query    DataQuery 数据查询接口
	DataQuery(ctx context.Context, req *QueryRequest, opts ...client.Option) (rsp *QueryResponse, err error) // ------------------------------ query end ------------------------------
	// DataChange @alias=/data/change    DataChange  数据变化查询接口
	DataChange(ctx context.Context, req *ChangeRequest, opts ...client.Option) (rsp *ChangeResponse, err error)
	// DataPointChange @alias=/data/pointChange    DataPointChange  变化测点查询接口
	DataPointChange(ctx context.Context, req *PointChangeRequest, opts ...client.Option) (rsp *PointChangeResponse, err error) // ------------------------------ change end ------------------------------
}

type DataClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewDataClientProxy = func(opts ...client.Option) DataClientProxy {
	return &DataClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *DataClientProxyImpl) DataQuery(ctx context.Context, req *QueryRequest, opts ...client.Option) (*QueryResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/data/query")
	msg.WithCalleeServiceName(DataServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Data")
	msg.WithCalleeMethod("DataQuery")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataClientProxyImpl) DataChange(ctx context.Context, req *ChangeRequest, opts ...client.Option) (*ChangeResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/data/change")
	msg.WithCalleeServiceName(DataServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Data")
	msg.WithCalleeMethod("DataChange")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ChangeResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataClientProxyImpl) DataPointChange(ctx context.Context, req *PointChangeRequest, opts ...client.Option) (*PointChangeResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/data/pointChange")
	msg.WithCalleeServiceName(DataServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Data")
	msg.WithCalleeMethod("DataPointChange")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PointChangeResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
