// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/tboxmonitor/tboxmonitor.proto

package tboxmonitor

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// MonitorService defines service.
type MonitorService interface {
	// Heartbeat @alias=/Monitor/Heartbeat
	Heartbeat(ctx context.Context, req *RequestHeartbeat) (*ResponseHeartbeat, error)
}

func MonitorService_Heartbeat_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RequestHeartbeat{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(MonitorService).Heartbeat(ctx, reqbody.(*RequestHeartbeat))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// MonitorServer_ServiceDesc descriptor for server.RegisterService.
var MonitorServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.tboxmonitor.Monitor",
	HandlerType: ((*MonitorService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Monitor/Heartbeat",
			Func: MonitorService_Heartbeat_Handler,
		},
		{
			Name: "/tbos.tboxmonitor.Monitor/Heartbeat",
			Func: MonitorService_Heartbeat_Handler,
		},
	},
}

// RegisterMonitorService registers service.
func RegisterMonitorService(s server.Service, svr MonitorService) {
	if err := s.Register(&MonitorServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Monitor register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedMonitor struct{}

// Heartbeat @alias=/Monitor/Heartbeat
func (s *UnimplementedMonitor) Heartbeat(ctx context.Context, req *RequestHeartbeat) (*ResponseHeartbeat, error) {
	return nil, errors.New("rpc Heartbeat of service Monitor is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// MonitorClientProxy defines service client proxy
type MonitorClientProxy interface {
	// Heartbeat @alias=/Monitor/Heartbeat
	Heartbeat(ctx context.Context, req *RequestHeartbeat, opts ...client.Option) (rsp *ResponseHeartbeat, err error)
}

type MonitorClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewMonitorClientProxy = func(opts ...client.Option) MonitorClientProxy {
	return &MonitorClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *MonitorClientProxyImpl) Heartbeat(ctx context.Context, req *RequestHeartbeat, opts ...client.Option) (*ResponseHeartbeat, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Monitor/Heartbeat")
	msg.WithCalleeServiceName(MonitorServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Monitor")
	msg.WithCalleeMethod("Heartbeat")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ResponseHeartbeat{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
