// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: cgi.proto

package cgi

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AlarmService defines service.
type AlarmService interface {
	// GetAlarmCnt @alias=/alarm/server/GetAlarmCnt    告警数量信息
	GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt) (*RspAlarmCnt, error)
	// GetAlarmCntTrend @alias=/alarm/server/GetAlarmCntTrend      过去24小时内告警数量信息
	GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend) (*RspAlarmCntTrend, error)
	// GetAlarmList @alias=/alarm/server/GetAlarmList   告警列表
	GetAlarmList(ctx context.Context, req *ReqAlarmList) (*RspAlarmList, error)
	// GetAlarmName @alias=/alarm/server/GetAlarmName   告警名称
	GetAlarmName(ctx context.Context, req *ReqAlarmName) (*RspAlarmName, error)
	// GetStrategy @alias=/alarm/server/GetStrategy   告警策略
	GetStrategy(ctx context.Context, req *ReqStrategyList) (*RspStrategyList, error)
	// GetStrategyInstance @alias=/alarm/server/GetStrategyInstance   告警策略实例
	GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance) (*RspStrategyInstance, error)
	// GetValidate @alias=/alarm/server/GetValidate   策略生效信息
	GetValidate(ctx context.Context, req *ReqValidateList) (*RspValidateList, error)
	// GetVirtualPoint @alias=/alarm/server/GetVirtualPoint       读取虚拟测点信息
	GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint) (*RspGetVirtualPoint, error)
}

func AlarmService_GetAlarmCnt_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmCnt{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetAlarmCnt(ctx, reqbody.(*ReqAlarmCnt))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmService_GetAlarmCntTrend_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmCntTrend{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetAlarmCntTrend(ctx, reqbody.(*ReqAlarmCntTrend))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmService_GetAlarmList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmList{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetAlarmList(ctx, reqbody.(*ReqAlarmList))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmService_GetAlarmName_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmName{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetAlarmName(ctx, reqbody.(*ReqAlarmName))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmService_GetStrategy_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqStrategyList{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetStrategy(ctx, reqbody.(*ReqStrategyList))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmService_GetStrategyInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqStrategyInstance{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetStrategyInstance(ctx, reqbody.(*ReqStrategyInstance))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmService_GetValidate_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqValidateList{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetValidate(ctx, reqbody.(*ReqValidateList))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmService_GetVirtualPoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetVirtualPoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmService).GetVirtualPoint(ctx, reqbody.(*ReqGetVirtualPoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AlarmServer_ServiceDesc descriptor for server.RegisterService.
var AlarmServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.cgi.Alarm",
	HandlerType: ((*AlarmService)(nil)),
	Methods: []server.Method{
		{
			Name: "/alarm/server/GetAlarmCnt",
			Func: AlarmService_GetAlarmCnt_Handler,
		},
		{
			Name: "/alarm/server/GetAlarmCntTrend",
			Func: AlarmService_GetAlarmCntTrend_Handler,
		},
		{
			Name: "/alarm/server/GetAlarmList",
			Func: AlarmService_GetAlarmList_Handler,
		},
		{
			Name: "/alarm/server/GetAlarmName",
			Func: AlarmService_GetAlarmName_Handler,
		},
		{
			Name: "/alarm/server/GetStrategy",
			Func: AlarmService_GetStrategy_Handler,
		},
		{
			Name: "/alarm/server/GetStrategyInstance",
			Func: AlarmService_GetStrategyInstance_Handler,
		},
		{
			Name: "/alarm/server/GetValidate",
			Func: AlarmService_GetValidate_Handler,
		},
		{
			Name: "/alarm/server/GetVirtualPoint",
			Func: AlarmService_GetVirtualPoint_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetAlarmCnt",
			Func: AlarmService_GetAlarmCnt_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetAlarmCntTrend",
			Func: AlarmService_GetAlarmCntTrend_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetAlarmList",
			Func: AlarmService_GetAlarmList_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetAlarmName",
			Func: AlarmService_GetAlarmName_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetStrategy",
			Func: AlarmService_GetStrategy_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetStrategyInstance",
			Func: AlarmService_GetStrategyInstance_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetValidate",
			Func: AlarmService_GetValidate_Handler,
		},
		{
			Name: "/tbos.cgi.Alarm/GetVirtualPoint",
			Func: AlarmService_GetVirtualPoint_Handler,
		},
	},
}

// RegisterAlarmService registers service.
func RegisterAlarmService(s server.Service, svr AlarmService) {
	if err := s.Register(&AlarmServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Alarm register error:%v", err))
	}
}

// CmdbService defines service.
type CmdbService interface {
	// GetDeviceEntity @alias=/Cmdb/GetDeviceEntity    获取设备列表
	GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity) (*RspGetDeviceEntity, error)
	// GetDeviceTree @alias=/Cmdb/GetDeviceTree    获取设备树
	GetDeviceTree(ctx context.Context, req *ReqGetDeviceTree) (*RspGetDeviceTree, error)
	// GetSubTree @alias=/Cmdb/GetSubTree    获取设备子树
	GetSubTree(ctx context.Context, req *ReqGetSubTree) (*RspGetSubTree, error)
	// GetDevicePoint @alias=/Cmdb/GetDevicePoint    获取测点信息
	GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint) (*RspGetDevicePoint, error)
	// GetSubTreeFieldDic @alias=/Cmdb/GetSubTreeFieldDic 获取子树字段字典
	GetSubTreeFieldDic(ctx context.Context, req *ReqGetSubTreeFieldDic) (*RspCommonGetKeyDict, error)
	// GetMozuInfo @alias=/Cmdb/GetMozuInfo 获取模组信息
	GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo) (*RspGetMozuInfo, error)
	// GetCollectorStatusTree @alias=/Cmdb/GetCollectorStatusTree 获取采集设备状态树
	GetCollectorStatusTree(ctx context.Context, req *ReqGetCollectorStatusTree) (*RspGetCollectorStatusTree, error)
	// GetCollectorInfo @alias=/Cmdb/GetCollectorInfo 获取采集设备信息
	GetCollectorInfo(ctx context.Context, req *ReqGetCollectorInfo) (*RspGetCollectorInfo, error)
	// GetCollectorPoint @alias=/Cmdb/GetCollectorPoint 获取采集设备测点信息
	GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint) (*RspGetCollectorPoint, error)
}

func CmdbService_GetDeviceEntity_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetDeviceEntity{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetDeviceEntity(ctx, reqbody.(*ReqGetDeviceEntity))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetDeviceTree_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetDeviceTree{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetDeviceTree(ctx, reqbody.(*ReqGetDeviceTree))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetSubTree_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetSubTree{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetSubTree(ctx, reqbody.(*ReqGetSubTree))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetDevicePoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetDevicePoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetDevicePoint(ctx, reqbody.(*ReqGetDevicePoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetSubTreeFieldDic_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetSubTreeFieldDic{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetSubTreeFieldDic(ctx, reqbody.(*ReqGetSubTreeFieldDic))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetMozuInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetMozuInfo{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetMozuInfo(ctx, reqbody.(*ReqGetMozuInfo))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetCollectorStatusTree_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetCollectorStatusTree{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetCollectorStatusTree(ctx, reqbody.(*ReqGetCollectorStatusTree))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetCollectorInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetCollectorInfo{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetCollectorInfo(ctx, reqbody.(*ReqGetCollectorInfo))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CmdbService_GetCollectorPoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetCollectorPoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CmdbService).GetCollectorPoint(ctx, reqbody.(*ReqGetCollectorPoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// CmdbServer_ServiceDesc descriptor for server.RegisterService.
var CmdbServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.cgi.Cmdb",
	HandlerType: ((*CmdbService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Cmdb/GetDeviceEntity",
			Func: CmdbService_GetDeviceEntity_Handler,
		},
		{
			Name: "/Cmdb/GetDeviceTree",
			Func: CmdbService_GetDeviceTree_Handler,
		},
		{
			Name: "/Cmdb/GetSubTree",
			Func: CmdbService_GetSubTree_Handler,
		},
		{
			Name: "/Cmdb/GetDevicePoint",
			Func: CmdbService_GetDevicePoint_Handler,
		},
		{
			Name: "/Cmdb/GetSubTreeFieldDic",
			Func: CmdbService_GetSubTreeFieldDic_Handler,
		},
		{
			Name: "/Cmdb/GetMozuInfo",
			Func: CmdbService_GetMozuInfo_Handler,
		},
		{
			Name: "/Cmdb/GetCollectorStatusTree",
			Func: CmdbService_GetCollectorStatusTree_Handler,
		},
		{
			Name: "/Cmdb/GetCollectorInfo",
			Func: CmdbService_GetCollectorInfo_Handler,
		},
		{
			Name: "/Cmdb/GetCollectorPoint",
			Func: CmdbService_GetCollectorPoint_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetDeviceEntity",
			Func: CmdbService_GetDeviceEntity_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetDeviceTree",
			Func: CmdbService_GetDeviceTree_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetSubTree",
			Func: CmdbService_GetSubTree_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetDevicePoint",
			Func: CmdbService_GetDevicePoint_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetSubTreeFieldDic",
			Func: CmdbService_GetSubTreeFieldDic_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetMozuInfo",
			Func: CmdbService_GetMozuInfo_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetCollectorStatusTree",
			Func: CmdbService_GetCollectorStatusTree_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetCollectorInfo",
			Func: CmdbService_GetCollectorInfo_Handler,
		},
		{
			Name: "/tbos.cgi.Cmdb/GetCollectorPoint",
			Func: CmdbService_GetCollectorPoint_Handler,
		},
	},
}

// RegisterCmdbService registers service.
func RegisterCmdbService(s server.Service, svr CmdbService) {
	if err := s.Register(&CmdbServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Cmdb register error:%v", err))
	}
}

// CommonService defines service.
type CommonService interface {
	// ExportData @alias=/Common/ExportData        导出数据
	ExportData(ctx context.Context, req *ReqCommonExportData) (*emptypb.Empty, error)
	// GetKeyDict @alias=/Common/GetKeyDict    获取配置字典-单字段
	GetKeyDict(ctx context.Context, req *ReqCommonGetDict) (*RspCommonGetKeyDict, error)
	// GetKvDict @alias=/Common/GetKvDict    获取配置字典-KV字段
	GetKvDict(ctx context.Context, req *ReqCommonGetDict) (*RspCommonGetKvDict, error)
}

func CommonService_ExportData_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqCommonExportData{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CommonService).ExportData(ctx, reqbody.(*ReqCommonExportData))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CommonService_GetKeyDict_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqCommonGetDict{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CommonService).GetKeyDict(ctx, reqbody.(*ReqCommonGetDict))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CommonService_GetKvDict_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqCommonGetDict{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CommonService).GetKvDict(ctx, reqbody.(*ReqCommonGetDict))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// CommonServer_ServiceDesc descriptor for server.RegisterService.
var CommonServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.cgi.Common",
	HandlerType: ((*CommonService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Common/ExportData",
			Func: CommonService_ExportData_Handler,
		},
		{
			Name: "/Common/GetKeyDict",
			Func: CommonService_GetKeyDict_Handler,
		},
		{
			Name: "/Common/GetKvDict",
			Func: CommonService_GetKvDict_Handler,
		},
		{
			Name: "/tbos.cgi.Common/ExportData",
			Func: CommonService_ExportData_Handler,
		},
		{
			Name: "/tbos.cgi.Common/GetKeyDict",
			Func: CommonService_GetKeyDict_Handler,
		},
		{
			Name: "/tbos.cgi.Common/GetKvDict",
			Func: CommonService_GetKvDict_Handler,
		},
	},
}

// RegisterCommonService registers service.
func RegisterCommonService(s server.Service, svr CommonService) {
	if err := s.Register(&CommonServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Common register error:%v", err))
	}
}

// DataService defines service.
type DataService interface {
	// Query @alias=/Data/Query    获取数据
	Query(ctx context.Context, req *ReqDataQuery) (*RspDataQuery, error)
	// TracePoint @alias=/Data/TracePoint    测点溯源
	TracePoint(ctx context.Context, req *ReqTracePoint) (*RspTracePoint, error)
	// QueryLatest @alias=/Data/QueryLatest    查询最新数据
	QueryLatest(ctx context.Context, req *ReqQueryLatest) (*RspQueryLatest, error)
}

func DataService_Query_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqDataQuery{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataService).Query(ctx, reqbody.(*ReqDataQuery))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataService_TracePoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqTracePoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataService).TracePoint(ctx, reqbody.(*ReqTracePoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataService_QueryLatest_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqQueryLatest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataService).QueryLatest(ctx, reqbody.(*ReqQueryLatest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// DataServer_ServiceDesc descriptor for server.RegisterService.
var DataServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.cgi.Data",
	HandlerType: ((*DataService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Data/Query",
			Func: DataService_Query_Handler,
		},
		{
			Name: "/Data/TracePoint",
			Func: DataService_TracePoint_Handler,
		},
		{
			Name: "/Data/QueryLatest",
			Func: DataService_QueryLatest_Handler,
		},
		{
			Name: "/tbos.cgi.Data/Query",
			Func: DataService_Query_Handler,
		},
		{
			Name: "/tbos.cgi.Data/TracePoint",
			Func: DataService_TracePoint_Handler,
		},
		{
			Name: "/tbos.cgi.Data/QueryLatest",
			Func: DataService_QueryLatest_Handler,
		},
	},
}

// RegisterDataService registers service.
func RegisterDataService(s server.Service, svr DataService) {
	if err := s.Register(&DataServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Data register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAlarm struct{}

// GetAlarmCnt @alias=/alarm/server/GetAlarmCnt    告警数量信息
func (s *UnimplementedAlarm) GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt) (*RspAlarmCnt, error) {
	return nil, errors.New("rpc GetAlarmCnt of service Alarm is not implemented")
}

// GetAlarmCntTrend @alias=/alarm/server/GetAlarmCntTrend      过去24小时内告警数量信息
func (s *UnimplementedAlarm) GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend) (*RspAlarmCntTrend, error) {
	return nil, errors.New("rpc GetAlarmCntTrend of service Alarm is not implemented")
}

// GetAlarmList @alias=/alarm/server/GetAlarmList   告警列表
func (s *UnimplementedAlarm) GetAlarmList(ctx context.Context, req *ReqAlarmList) (*RspAlarmList, error) {
	return nil, errors.New("rpc GetAlarmList of service Alarm is not implemented")
}

// GetAlarmName @alias=/alarm/server/GetAlarmName   告警名称
func (s *UnimplementedAlarm) GetAlarmName(ctx context.Context, req *ReqAlarmName) (*RspAlarmName, error) {
	return nil, errors.New("rpc GetAlarmName of service Alarm is not implemented")
}

// GetStrategy @alias=/alarm/server/GetStrategy   告警策略
func (s *UnimplementedAlarm) GetStrategy(ctx context.Context, req *ReqStrategyList) (*RspStrategyList, error) {
	return nil, errors.New("rpc GetStrategy of service Alarm is not implemented")
}

// GetStrategyInstance @alias=/alarm/server/GetStrategyInstance   告警策略实例
func (s *UnimplementedAlarm) GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance) (*RspStrategyInstance, error) {
	return nil, errors.New("rpc GetStrategyInstance of service Alarm is not implemented")
}

// GetValidate @alias=/alarm/server/GetValidate   策略生效信息
func (s *UnimplementedAlarm) GetValidate(ctx context.Context, req *ReqValidateList) (*RspValidateList, error) {
	return nil, errors.New("rpc GetValidate of service Alarm is not implemented")
}

// GetVirtualPoint @alias=/alarm/server/GetVirtualPoint       读取虚拟测点信息
func (s *UnimplementedAlarm) GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint) (*RspGetVirtualPoint, error) {
	return nil, errors.New("rpc GetVirtualPoint of service Alarm is not implemented")
}

type UnimplementedCmdb struct{}

// GetDeviceEntity @alias=/Cmdb/GetDeviceEntity    获取设备列表
func (s *UnimplementedCmdb) GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity) (*RspGetDeviceEntity, error) {
	return nil, errors.New("rpc GetDeviceEntity of service Cmdb is not implemented")
}

// GetDeviceTree @alias=/Cmdb/GetDeviceTree    获取设备树
func (s *UnimplementedCmdb) GetDeviceTree(ctx context.Context, req *ReqGetDeviceTree) (*RspGetDeviceTree, error) {
	return nil, errors.New("rpc GetDeviceTree of service Cmdb is not implemented")
}

// GetSubTree @alias=/Cmdb/GetSubTree    获取设备子树
func (s *UnimplementedCmdb) GetSubTree(ctx context.Context, req *ReqGetSubTree) (*RspGetSubTree, error) {
	return nil, errors.New("rpc GetSubTree of service Cmdb is not implemented")
}

// GetDevicePoint @alias=/Cmdb/GetDevicePoint    获取测点信息
func (s *UnimplementedCmdb) GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint) (*RspGetDevicePoint, error) {
	return nil, errors.New("rpc GetDevicePoint of service Cmdb is not implemented")
}

// GetSubTreeFieldDic @alias=/Cmdb/GetSubTreeFieldDic 获取子树字段字典
func (s *UnimplementedCmdb) GetSubTreeFieldDic(ctx context.Context, req *ReqGetSubTreeFieldDic) (*RspCommonGetKeyDict, error) {
	return nil, errors.New("rpc GetSubTreeFieldDic of service Cmdb is not implemented")
}

// GetMozuInfo @alias=/Cmdb/GetMozuInfo 获取模组信息
func (s *UnimplementedCmdb) GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo) (*RspGetMozuInfo, error) {
	return nil, errors.New("rpc GetMozuInfo of service Cmdb is not implemented")
}

// GetCollectorStatusTree @alias=/Cmdb/GetCollectorStatusTree 获取采集设备状态树
func (s *UnimplementedCmdb) GetCollectorStatusTree(ctx context.Context, req *ReqGetCollectorStatusTree) (*RspGetCollectorStatusTree, error) {
	return nil, errors.New("rpc GetCollectorStatusTree of service Cmdb is not implemented")
}

// GetCollectorInfo @alias=/Cmdb/GetCollectorInfo 获取采集设备信息
func (s *UnimplementedCmdb) GetCollectorInfo(ctx context.Context, req *ReqGetCollectorInfo) (*RspGetCollectorInfo, error) {
	return nil, errors.New("rpc GetCollectorInfo of service Cmdb is not implemented")
}

// GetCollectorPoint @alias=/Cmdb/GetCollectorPoint 获取采集设备测点信息
func (s *UnimplementedCmdb) GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint) (*RspGetCollectorPoint, error) {
	return nil, errors.New("rpc GetCollectorPoint of service Cmdb is not implemented")
}

type UnimplementedCommon struct{}

// ExportData @alias=/Common/ExportData        导出数据
func (s *UnimplementedCommon) ExportData(ctx context.Context, req *ReqCommonExportData) (*emptypb.Empty, error) {
	return nil, errors.New("rpc ExportData of service Common is not implemented")
}

// GetKeyDict @alias=/Common/GetKeyDict    获取配置字典-单字段
func (s *UnimplementedCommon) GetKeyDict(ctx context.Context, req *ReqCommonGetDict) (*RspCommonGetKeyDict, error) {
	return nil, errors.New("rpc GetKeyDict of service Common is not implemented")
}

// GetKvDict @alias=/Common/GetKvDict    获取配置字典-KV字段
func (s *UnimplementedCommon) GetKvDict(ctx context.Context, req *ReqCommonGetDict) (*RspCommonGetKvDict, error) {
	return nil, errors.New("rpc GetKvDict of service Common is not implemented")
}

type UnimplementedData struct{}

// Query @alias=/Data/Query    获取数据
func (s *UnimplementedData) Query(ctx context.Context, req *ReqDataQuery) (*RspDataQuery, error) {
	return nil, errors.New("rpc Query of service Data is not implemented")
}

// TracePoint @alias=/Data/TracePoint    测点溯源
func (s *UnimplementedData) TracePoint(ctx context.Context, req *ReqTracePoint) (*RspTracePoint, error) {
	return nil, errors.New("rpc TracePoint of service Data is not implemented")
}

// QueryLatest @alias=/Data/QueryLatest    查询最新数据
func (s *UnimplementedData) QueryLatest(ctx context.Context, req *ReqQueryLatest) (*RspQueryLatest, error) {
	return nil, errors.New("rpc QueryLatest of service Data is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AlarmClientProxy defines service client proxy
type AlarmClientProxy interface {
	// GetAlarmCnt @alias=/alarm/server/GetAlarmCnt    告警数量信息
	GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt, opts ...client.Option) (rsp *RspAlarmCnt, err error)
	// GetAlarmCntTrend @alias=/alarm/server/GetAlarmCntTrend      过去24小时内告警数量信息
	GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend, opts ...client.Option) (rsp *RspAlarmCntTrend, err error)
	// GetAlarmList @alias=/alarm/server/GetAlarmList   告警列表
	GetAlarmList(ctx context.Context, req *ReqAlarmList, opts ...client.Option) (rsp *RspAlarmList, err error)
	// GetAlarmName @alias=/alarm/server/GetAlarmName   告警名称
	GetAlarmName(ctx context.Context, req *ReqAlarmName, opts ...client.Option) (rsp *RspAlarmName, err error)
	// GetStrategy @alias=/alarm/server/GetStrategy   告警策略
	GetStrategy(ctx context.Context, req *ReqStrategyList, opts ...client.Option) (rsp *RspStrategyList, err error)
	// GetStrategyInstance @alias=/alarm/server/GetStrategyInstance   告警策略实例
	GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance, opts ...client.Option) (rsp *RspStrategyInstance, err error)
	// GetValidate @alias=/alarm/server/GetValidate   策略生效信息
	GetValidate(ctx context.Context, req *ReqValidateList, opts ...client.Option) (rsp *RspValidateList, err error)
	// GetVirtualPoint @alias=/alarm/server/GetVirtualPoint       读取虚拟测点信息
	GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint, opts ...client.Option) (rsp *RspGetVirtualPoint, err error)
}

type AlarmClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAlarmClientProxy = func(opts ...client.Option) AlarmClientProxy {
	return &AlarmClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AlarmClientProxyImpl) GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt, opts ...client.Option) (*RspAlarmCnt, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmCnt")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetAlarmCnt")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmCnt{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmClientProxyImpl) GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend, opts ...client.Option) (*RspAlarmCntTrend, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmCntTrend")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetAlarmCntTrend")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmCntTrend{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmClientProxyImpl) GetAlarmList(ctx context.Context, req *ReqAlarmList, opts ...client.Option) (*RspAlarmList, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmList")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetAlarmList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmList{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmClientProxyImpl) GetAlarmName(ctx context.Context, req *ReqAlarmName, opts ...client.Option) (*RspAlarmName, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmName")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetAlarmName")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmName{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmClientProxyImpl) GetStrategy(ctx context.Context, req *ReqStrategyList, opts ...client.Option) (*RspStrategyList, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetStrategy")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetStrategy")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspStrategyList{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmClientProxyImpl) GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance, opts ...client.Option) (*RspStrategyInstance, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetStrategyInstance")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetStrategyInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspStrategyInstance{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmClientProxyImpl) GetValidate(ctx context.Context, req *ReqValidateList, opts ...client.Option) (*RspValidateList, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetValidate")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetValidate")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspValidateList{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmClientProxyImpl) GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint, opts ...client.Option) (*RspGetVirtualPoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetVirtualPoint")
	msg.WithCalleeServiceName(AlarmServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Alarm")
	msg.WithCalleeMethod("GetVirtualPoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetVirtualPoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// CmdbClientProxy defines service client proxy
type CmdbClientProxy interface {
	// GetDeviceEntity @alias=/Cmdb/GetDeviceEntity    获取设备列表
	GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity, opts ...client.Option) (rsp *RspGetDeviceEntity, err error)
	// GetDeviceTree @alias=/Cmdb/GetDeviceTree    获取设备树
	GetDeviceTree(ctx context.Context, req *ReqGetDeviceTree, opts ...client.Option) (rsp *RspGetDeviceTree, err error)
	// GetSubTree @alias=/Cmdb/GetSubTree    获取设备子树
	GetSubTree(ctx context.Context, req *ReqGetSubTree, opts ...client.Option) (rsp *RspGetSubTree, err error)
	// GetDevicePoint @alias=/Cmdb/GetDevicePoint    获取测点信息
	GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint, opts ...client.Option) (rsp *RspGetDevicePoint, err error)
	// GetSubTreeFieldDic @alias=/Cmdb/GetSubTreeFieldDic 获取子树字段字典
	GetSubTreeFieldDic(ctx context.Context, req *ReqGetSubTreeFieldDic, opts ...client.Option) (rsp *RspCommonGetKeyDict, err error)
	// GetMozuInfo @alias=/Cmdb/GetMozuInfo 获取模组信息
	GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo, opts ...client.Option) (rsp *RspGetMozuInfo, err error)
	// GetCollectorStatusTree @alias=/Cmdb/GetCollectorStatusTree 获取采集设备状态树
	GetCollectorStatusTree(ctx context.Context, req *ReqGetCollectorStatusTree, opts ...client.Option) (rsp *RspGetCollectorStatusTree, err error)
	// GetCollectorInfo @alias=/Cmdb/GetCollectorInfo 获取采集设备信息
	GetCollectorInfo(ctx context.Context, req *ReqGetCollectorInfo, opts ...client.Option) (rsp *RspGetCollectorInfo, err error)
	// GetCollectorPoint @alias=/Cmdb/GetCollectorPoint 获取采集设备测点信息
	GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint, opts ...client.Option) (rsp *RspGetCollectorPoint, err error)
}

type CmdbClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewCmdbClientProxy = func(opts ...client.Option) CmdbClientProxy {
	return &CmdbClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *CmdbClientProxyImpl) GetDeviceEntity(ctx context.Context, req *ReqGetDeviceEntity, opts ...client.Option) (*RspGetDeviceEntity, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetDeviceEntity")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetDeviceEntity")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetDeviceEntity{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetDeviceTree(ctx context.Context, req *ReqGetDeviceTree, opts ...client.Option) (*RspGetDeviceTree, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetDeviceTree")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetDeviceTree")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetDeviceTree{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetSubTree(ctx context.Context, req *ReqGetSubTree, opts ...client.Option) (*RspGetSubTree, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetSubTree")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetSubTree")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetSubTree{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetDevicePoint(ctx context.Context, req *ReqGetDevicePoint, opts ...client.Option) (*RspGetDevicePoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetDevicePoint")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetDevicePoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetDevicePoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetSubTreeFieldDic(ctx context.Context, req *ReqGetSubTreeFieldDic, opts ...client.Option) (*RspCommonGetKeyDict, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetSubTreeFieldDic")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetSubTreeFieldDic")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspCommonGetKeyDict{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetMozuInfo(ctx context.Context, req *ReqGetMozuInfo, opts ...client.Option) (*RspGetMozuInfo, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetMozuInfo")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetMozuInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetMozuInfo{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetCollectorStatusTree(ctx context.Context, req *ReqGetCollectorStatusTree, opts ...client.Option) (*RspGetCollectorStatusTree, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetCollectorStatusTree")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetCollectorStatusTree")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetCollectorStatusTree{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetCollectorInfo(ctx context.Context, req *ReqGetCollectorInfo, opts ...client.Option) (*RspGetCollectorInfo, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetCollectorInfo")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetCollectorInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetCollectorInfo{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CmdbClientProxyImpl) GetCollectorPoint(ctx context.Context, req *ReqGetCollectorPoint, opts ...client.Option) (*RspGetCollectorPoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Cmdb/GetCollectorPoint")
	msg.WithCalleeServiceName(CmdbServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Cmdb")
	msg.WithCalleeMethod("GetCollectorPoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetCollectorPoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// CommonClientProxy defines service client proxy
type CommonClientProxy interface {
	// ExportData @alias=/Common/ExportData        导出数据
	ExportData(ctx context.Context, req *ReqCommonExportData, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// GetKeyDict @alias=/Common/GetKeyDict    获取配置字典-单字段
	GetKeyDict(ctx context.Context, req *ReqCommonGetDict, opts ...client.Option) (rsp *RspCommonGetKeyDict, err error)
	// GetKvDict @alias=/Common/GetKvDict    获取配置字典-KV字段
	GetKvDict(ctx context.Context, req *ReqCommonGetDict, opts ...client.Option) (rsp *RspCommonGetKvDict, err error)
}

type CommonClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewCommonClientProxy = func(opts ...client.Option) CommonClientProxy {
	return &CommonClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *CommonClientProxyImpl) ExportData(ctx context.Context, req *ReqCommonExportData, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Common/ExportData")
	msg.WithCalleeServiceName(CommonServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Common")
	msg.WithCalleeMethod("ExportData")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CommonClientProxyImpl) GetKeyDict(ctx context.Context, req *ReqCommonGetDict, opts ...client.Option) (*RspCommonGetKeyDict, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Common/GetKeyDict")
	msg.WithCalleeServiceName(CommonServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Common")
	msg.WithCalleeMethod("GetKeyDict")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspCommonGetKeyDict{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CommonClientProxyImpl) GetKvDict(ctx context.Context, req *ReqCommonGetDict, opts ...client.Option) (*RspCommonGetKvDict, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Common/GetKvDict")
	msg.WithCalleeServiceName(CommonServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Common")
	msg.WithCalleeMethod("GetKvDict")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspCommonGetKvDict{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// DataClientProxy defines service client proxy
type DataClientProxy interface {
	// Query @alias=/Data/Query    获取数据
	Query(ctx context.Context, req *ReqDataQuery, opts ...client.Option) (rsp *RspDataQuery, err error)
	// TracePoint @alias=/Data/TracePoint    测点溯源
	TracePoint(ctx context.Context, req *ReqTracePoint, opts ...client.Option) (rsp *RspTracePoint, err error)
	// QueryLatest @alias=/Data/QueryLatest    查询最新数据
	QueryLatest(ctx context.Context, req *ReqQueryLatest, opts ...client.Option) (rsp *RspQueryLatest, err error)
}

type DataClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewDataClientProxy = func(opts ...client.Option) DataClientProxy {
	return &DataClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *DataClientProxyImpl) Query(ctx context.Context, req *ReqDataQuery, opts ...client.Option) (*RspDataQuery, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Data/Query")
	msg.WithCalleeServiceName(DataServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Data")
	msg.WithCalleeMethod("Query")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspDataQuery{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataClientProxyImpl) TracePoint(ctx context.Context, req *ReqTracePoint, opts ...client.Option) (*RspTracePoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Data/TracePoint")
	msg.WithCalleeServiceName(DataServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Data")
	msg.WithCalleeMethod("TracePoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspTracePoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataClientProxyImpl) QueryLatest(ctx context.Context, req *ReqQueryLatest, opts ...client.Option) (*RspQueryLatest, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Data/QueryLatest")
	msg.WithCalleeServiceName(DataServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Data")
	msg.WithCalleeMethod("QueryLatest")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspQueryLatest{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
