// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/alarm-server/alarm-server.proto

package alarm_server

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AlarmServerService defines service.
type AlarmServerService interface {
	// GetAlarmCnt @alias=/alarm/server/GetAlarmCnt           告警数量信息
	GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt) (*RspAlarmCnt, error)
	// GetAlarmCntTrend @alias=/alarm/server/GetAlarmCntTrend      过去24小时内告警数量信息
	GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend) (*RspAlarmCntTrend, error)
	// GetAlarmList @alias=/alarm/server/GetAlarmList          告警列表
	GetAlarmList(ctx context.Context, req *ReqAlarmList) (*RspAlarmList, error)
	// GetAlarmName @alias=/alarm/server/GetAlarmName          告警名称
	GetAlarmName(ctx context.Context, req *ReqAlarmName) (*RspAlarmName, error)
	// GetStrategy @alias=/alarm/server/GetStrategy           告警策略
	GetStrategy(ctx context.Context, req *ReqStrategyList) (*RspStrategyList, error)
	// GetStrategyInstance @alias=/alarm/server/GetStrategyInstance   告警策略实例
	GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance) (*RspStrategyInstance, error)
	// GetValidate @alias=/alarm/server/GetValidate           策略生效信息
	GetValidate(ctx context.Context, req *ReqValidateList) (*RspValidateList, error)
	// UpdateAlarmStatus @alias=/alarm/server/UpdateAlarmStatus     解除挂起告警
	UpdateAlarmStatus(ctx context.Context, req *ReqUpdateAlarmStatus) (*emptypb.Empty, error)
	// GetVirtualPoint @alias=/alarm/server/GetVirtualPoint       读取虚拟测点信息
	GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint) (*RspGetVirtualPoint, error)
	// DelHistoryAlarm @alias=/alarm/server/DelHistoryAlarm       删除历史告警
	DelHistoryAlarm(ctx context.Context, req *ReqDelHistoryAlarm) (*emptypb.Empty, error)
	// AlarmDiagnose @alias=/alarm/server/AlarmDiagnose       告警回放
	AlarmDiagnose(ctx context.Context, req *ReqAlarmDiagnose) (*RspAlarmDiagnose, error)
}

func AlarmServerService_GetAlarmCnt_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmCnt{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetAlarmCnt(ctx, reqbody.(*ReqAlarmCnt))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_GetAlarmCntTrend_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmCntTrend{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetAlarmCntTrend(ctx, reqbody.(*ReqAlarmCntTrend))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_GetAlarmList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmList{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetAlarmList(ctx, reqbody.(*ReqAlarmList))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_GetAlarmName_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmName{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetAlarmName(ctx, reqbody.(*ReqAlarmName))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_GetStrategy_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqStrategyList{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetStrategy(ctx, reqbody.(*ReqStrategyList))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_GetStrategyInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqStrategyInstance{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetStrategyInstance(ctx, reqbody.(*ReqStrategyInstance))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_GetValidate_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqValidateList{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetValidate(ctx, reqbody.(*ReqValidateList))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_UpdateAlarmStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqUpdateAlarmStatus{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).UpdateAlarmStatus(ctx, reqbody.(*ReqUpdateAlarmStatus))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_GetVirtualPoint_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqGetVirtualPoint{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).GetVirtualPoint(ctx, reqbody.(*ReqGetVirtualPoint))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_DelHistoryAlarm_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqDelHistoryAlarm{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).DelHistoryAlarm(ctx, reqbody.(*ReqDelHistoryAlarm))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmServerService_AlarmDiagnose_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqAlarmDiagnose{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmServerService).AlarmDiagnose(ctx, reqbody.(*ReqAlarmDiagnose))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AlarmServerServer_ServiceDesc descriptor for server.RegisterService.
var AlarmServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.alarm.AlarmServer",
	HandlerType: ((*AlarmServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/alarm/server/GetAlarmCnt",
			Func: AlarmServerService_GetAlarmCnt_Handler,
		},
		{
			Name: "/alarm/server/GetAlarmCntTrend",
			Func: AlarmServerService_GetAlarmCntTrend_Handler,
		},
		{
			Name: "/alarm/server/GetAlarmList",
			Func: AlarmServerService_GetAlarmList_Handler,
		},
		{
			Name: "/alarm/server/GetAlarmName",
			Func: AlarmServerService_GetAlarmName_Handler,
		},
		{
			Name: "/alarm/server/GetStrategy",
			Func: AlarmServerService_GetStrategy_Handler,
		},
		{
			Name: "/alarm/server/GetStrategyInstance",
			Func: AlarmServerService_GetStrategyInstance_Handler,
		},
		{
			Name: "/alarm/server/GetValidate",
			Func: AlarmServerService_GetValidate_Handler,
		},
		{
			Name: "/alarm/server/UpdateAlarmStatus",
			Func: AlarmServerService_UpdateAlarmStatus_Handler,
		},
		{
			Name: "/alarm/server/GetVirtualPoint",
			Func: AlarmServerService_GetVirtualPoint_Handler,
		},
		{
			Name: "/alarm/server/DelHistoryAlarm",
			Func: AlarmServerService_DelHistoryAlarm_Handler,
		},
		{
			Name: "/alarm/server/AlarmDiagnose",
			Func: AlarmServerService_AlarmDiagnose_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetAlarmCnt",
			Func: AlarmServerService_GetAlarmCnt_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetAlarmCntTrend",
			Func: AlarmServerService_GetAlarmCntTrend_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetAlarmList",
			Func: AlarmServerService_GetAlarmList_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetAlarmName",
			Func: AlarmServerService_GetAlarmName_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetStrategy",
			Func: AlarmServerService_GetStrategy_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetStrategyInstance",
			Func: AlarmServerService_GetStrategyInstance_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetValidate",
			Func: AlarmServerService_GetValidate_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/UpdateAlarmStatus",
			Func: AlarmServerService_UpdateAlarmStatus_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/GetVirtualPoint",
			Func: AlarmServerService_GetVirtualPoint_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/DelHistoryAlarm",
			Func: AlarmServerService_DelHistoryAlarm_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmServer/AlarmDiagnose",
			Func: AlarmServerService_AlarmDiagnose_Handler,
		},
	},
}

// RegisterAlarmServerService registers service.
func RegisterAlarmServerService(s server.Service, svr AlarmServerService) {
	if err := s.Register(&AlarmServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AlarmServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAlarmServer struct{}

// GetAlarmCnt @alias=/alarm/server/GetAlarmCnt           告警数量信息
func (s *UnimplementedAlarmServer) GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt) (*RspAlarmCnt, error) {
	return nil, errors.New("rpc GetAlarmCnt of service AlarmServer is not implemented")
}

// GetAlarmCntTrend @alias=/alarm/server/GetAlarmCntTrend      过去24小时内告警数量信息
func (s *UnimplementedAlarmServer) GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend) (*RspAlarmCntTrend, error) {
	return nil, errors.New("rpc GetAlarmCntTrend of service AlarmServer is not implemented")
}

// GetAlarmList @alias=/alarm/server/GetAlarmList          告警列表
func (s *UnimplementedAlarmServer) GetAlarmList(ctx context.Context, req *ReqAlarmList) (*RspAlarmList, error) {
	return nil, errors.New("rpc GetAlarmList of service AlarmServer is not implemented")
}

// GetAlarmName @alias=/alarm/server/GetAlarmName          告警名称
func (s *UnimplementedAlarmServer) GetAlarmName(ctx context.Context, req *ReqAlarmName) (*RspAlarmName, error) {
	return nil, errors.New("rpc GetAlarmName of service AlarmServer is not implemented")
}

// GetStrategy @alias=/alarm/server/GetStrategy           告警策略
func (s *UnimplementedAlarmServer) GetStrategy(ctx context.Context, req *ReqStrategyList) (*RspStrategyList, error) {
	return nil, errors.New("rpc GetStrategy of service AlarmServer is not implemented")
}

// GetStrategyInstance @alias=/alarm/server/GetStrategyInstance   告警策略实例
func (s *UnimplementedAlarmServer) GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance) (*RspStrategyInstance, error) {
	return nil, errors.New("rpc GetStrategyInstance of service AlarmServer is not implemented")
}

// GetValidate @alias=/alarm/server/GetValidate           策略生效信息
func (s *UnimplementedAlarmServer) GetValidate(ctx context.Context, req *ReqValidateList) (*RspValidateList, error) {
	return nil, errors.New("rpc GetValidate of service AlarmServer is not implemented")
}

// UpdateAlarmStatus @alias=/alarm/server/UpdateAlarmStatus     解除挂起告警
func (s *UnimplementedAlarmServer) UpdateAlarmStatus(ctx context.Context, req *ReqUpdateAlarmStatus) (*emptypb.Empty, error) {
	return nil, errors.New("rpc UpdateAlarmStatus of service AlarmServer is not implemented")
}

// GetVirtualPoint @alias=/alarm/server/GetVirtualPoint       读取虚拟测点信息
func (s *UnimplementedAlarmServer) GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint) (*RspGetVirtualPoint, error) {
	return nil, errors.New("rpc GetVirtualPoint of service AlarmServer is not implemented")
}

// DelHistoryAlarm @alias=/alarm/server/DelHistoryAlarm       删除历史告警
func (s *UnimplementedAlarmServer) DelHistoryAlarm(ctx context.Context, req *ReqDelHistoryAlarm) (*emptypb.Empty, error) {
	return nil, errors.New("rpc DelHistoryAlarm of service AlarmServer is not implemented")
}

// AlarmDiagnose @alias=/alarm/server/AlarmDiagnose       告警回放
func (s *UnimplementedAlarmServer) AlarmDiagnose(ctx context.Context, req *ReqAlarmDiagnose) (*RspAlarmDiagnose, error) {
	return nil, errors.New("rpc AlarmDiagnose of service AlarmServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AlarmServerClientProxy defines service client proxy
type AlarmServerClientProxy interface {
	// GetAlarmCnt @alias=/alarm/server/GetAlarmCnt           告警数量信息
	GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt, opts ...client.Option) (rsp *RspAlarmCnt, err error)
	// GetAlarmCntTrend @alias=/alarm/server/GetAlarmCntTrend      过去24小时内告警数量信息
	GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend, opts ...client.Option) (rsp *RspAlarmCntTrend, err error)
	// GetAlarmList @alias=/alarm/server/GetAlarmList          告警列表
	GetAlarmList(ctx context.Context, req *ReqAlarmList, opts ...client.Option) (rsp *RspAlarmList, err error)
	// GetAlarmName @alias=/alarm/server/GetAlarmName          告警名称
	GetAlarmName(ctx context.Context, req *ReqAlarmName, opts ...client.Option) (rsp *RspAlarmName, err error)
	// GetStrategy @alias=/alarm/server/GetStrategy           告警策略
	GetStrategy(ctx context.Context, req *ReqStrategyList, opts ...client.Option) (rsp *RspStrategyList, err error)
	// GetStrategyInstance @alias=/alarm/server/GetStrategyInstance   告警策略实例
	GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance, opts ...client.Option) (rsp *RspStrategyInstance, err error)
	// GetValidate @alias=/alarm/server/GetValidate           策略生效信息
	GetValidate(ctx context.Context, req *ReqValidateList, opts ...client.Option) (rsp *RspValidateList, err error)
	// UpdateAlarmStatus @alias=/alarm/server/UpdateAlarmStatus     解除挂起告警
	UpdateAlarmStatus(ctx context.Context, req *ReqUpdateAlarmStatus, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// GetVirtualPoint @alias=/alarm/server/GetVirtualPoint       读取虚拟测点信息
	GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint, opts ...client.Option) (rsp *RspGetVirtualPoint, err error)
	// DelHistoryAlarm @alias=/alarm/server/DelHistoryAlarm       删除历史告警
	DelHistoryAlarm(ctx context.Context, req *ReqDelHistoryAlarm, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// AlarmDiagnose @alias=/alarm/server/AlarmDiagnose       告警回放
	AlarmDiagnose(ctx context.Context, req *ReqAlarmDiagnose, opts ...client.Option) (rsp *RspAlarmDiagnose, err error)
}

type AlarmServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAlarmServerClientProxy = func(opts ...client.Option) AlarmServerClientProxy {
	return &AlarmServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AlarmServerClientProxyImpl) GetAlarmCnt(ctx context.Context, req *ReqAlarmCnt, opts ...client.Option) (*RspAlarmCnt, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmCnt")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetAlarmCnt")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmCnt{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) GetAlarmCntTrend(ctx context.Context, req *ReqAlarmCntTrend, opts ...client.Option) (*RspAlarmCntTrend, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmCntTrend")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetAlarmCntTrend")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmCntTrend{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) GetAlarmList(ctx context.Context, req *ReqAlarmList, opts ...client.Option) (*RspAlarmList, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmList")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetAlarmList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmList{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) GetAlarmName(ctx context.Context, req *ReqAlarmName, opts ...client.Option) (*RspAlarmName, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetAlarmName")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetAlarmName")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmName{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) GetStrategy(ctx context.Context, req *ReqStrategyList, opts ...client.Option) (*RspStrategyList, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetStrategy")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetStrategy")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspStrategyList{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) GetStrategyInstance(ctx context.Context, req *ReqStrategyInstance, opts ...client.Option) (*RspStrategyInstance, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetStrategyInstance")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetStrategyInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspStrategyInstance{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) GetValidate(ctx context.Context, req *ReqValidateList, opts ...client.Option) (*RspValidateList, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetValidate")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetValidate")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspValidateList{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) UpdateAlarmStatus(ctx context.Context, req *ReqUpdateAlarmStatus, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/UpdateAlarmStatus")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("UpdateAlarmStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) GetVirtualPoint(ctx context.Context, req *ReqGetVirtualPoint, opts ...client.Option) (*RspGetVirtualPoint, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/GetVirtualPoint")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("GetVirtualPoint")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspGetVirtualPoint{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) DelHistoryAlarm(ctx context.Context, req *ReqDelHistoryAlarm, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/DelHistoryAlarm")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("DelHistoryAlarm")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmServerClientProxyImpl) AlarmDiagnose(ctx context.Context, req *ReqAlarmDiagnose, opts ...client.Option) (*RspAlarmDiagnose, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/alarm/server/AlarmDiagnose")
	msg.WithCalleeServiceName(AlarmServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmServer")
	msg.WithCalleeMethod("AlarmDiagnose")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspAlarmDiagnose{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
