// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trpcprotocol/alarm-compute/alarm-compute.proto

package alarm_compute

import (
	"context"
	"errors"
	"fmt"

	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AlarmComputeService defines service.
type AlarmComputeService interface {
	// RecvTask @alias=/Strategy/RecvTask
	RecvTask(ctx context.Context, req *ReqStrategyRecv) (*emptypb.Empty, error)
	// ExpCompute @alias=/Alarm/ExpCompute
	ExpCompute(ctx context.Context, req *ReqExpCompute) (*RspExpCompute, error)
}

func AlarmComputeService_RecvTask_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqStrategyRecv{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmComputeService).RecvTask(ctx, reqbody.(*ReqStrategyRecv))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AlarmComputeService_ExpCompute_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReqExpCompute{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AlarmComputeService).ExpCompute(ctx, reqbody.(*ReqExpCompute))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AlarmComputeServer_ServiceDesc descriptor for server.RegisterService.
var AlarmComputeServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "tbos.alarm.AlarmCompute",
	HandlerType: ((*AlarmComputeService)(nil)),
	Methods: []server.Method{
		{
			Name: "/Strategy/RecvTask",
			Func: AlarmComputeService_RecvTask_Handler,
		},
		{
			Name: "/Alarm/ExpCompute",
			Func: AlarmComputeService_ExpCompute_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmCompute/RecvTask",
			Func: AlarmComputeService_RecvTask_Handler,
		},
		{
			Name: "/tbos.alarm.AlarmCompute/ExpCompute",
			Func: AlarmComputeService_ExpCompute_Handler,
		},
	},
}

// RegisterAlarmComputeService registers service.
func RegisterAlarmComputeService(s server.Service, svr AlarmComputeService) {
	if err := s.Register(&AlarmComputeServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AlarmCompute register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAlarmCompute struct{}

// RecvTask @alias=/Strategy/RecvTask
func (s *UnimplementedAlarmCompute) RecvTask(ctx context.Context, req *ReqStrategyRecv) (*emptypb.Empty, error) {
	return nil, errors.New("rpc RecvTask of service AlarmCompute is not implemented")
}

// ExpCompute @alias=/Alarm/ExpCompute
func (s *UnimplementedAlarmCompute) ExpCompute(ctx context.Context, req *ReqExpCompute) (*RspExpCompute, error) {
	return nil, errors.New("rpc ExpCompute of service AlarmCompute is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AlarmComputeClientProxy defines service client proxy
type AlarmComputeClientProxy interface {
	// RecvTask @alias=/Strategy/RecvTask
	RecvTask(ctx context.Context, req *ReqStrategyRecv, opts ...client.Option) (rsp *emptypb.Empty, err error)
	// ExpCompute @alias=/Alarm/ExpCompute
	ExpCompute(ctx context.Context, req *ReqExpCompute, opts ...client.Option) (rsp *RspExpCompute, err error)
}

type AlarmComputeClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAlarmComputeClientProxy = func(opts ...client.Option) AlarmComputeClientProxy {
	return &AlarmComputeClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AlarmComputeClientProxyImpl) RecvTask(ctx context.Context, req *ReqStrategyRecv, opts ...client.Option) (*emptypb.Empty, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Strategy/RecvTask")
	msg.WithCalleeServiceName(AlarmComputeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmCompute")
	msg.WithCalleeMethod("RecvTask")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &emptypb.Empty{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AlarmComputeClientProxyImpl) ExpCompute(ctx context.Context, req *ReqExpCompute, opts ...client.Option) (*RspExpCompute, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/Alarm/ExpCompute")
	msg.WithCalleeServiceName(AlarmComputeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AlarmCompute")
	msg.WithCalleeMethod("ExpCompute")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RspExpCompute{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
