import business from '@@/config/business';

const colorMap = {
  L0: '#ff3e00',
  L1: '#FF3E00',
  L2: '#FF7A0D',
  L3: '#FFB20D',
  L4: '#0080FF',
  L5: '#8acbf2',
};

const v1Columns = window.tnwebServices.isTbos
  ? [{
    name: 'protocolTypeName',
    label: '设备类型',
    isFilter: false,
    size: 10,
    max: 20,
    seqNumber: 1,
    showInTable: true,
    showInSearch: false,
    type: 'singleSelect',
    dropdownMethod: 'post',
    dropdownPath: '/cgi/idc-tbos-cgi/Common/GetKvDict',
    dropdownQuery: () => ({ dic_type: 'device_type_kv' }),
    dropdownFormatter: (data) => {
      const originalObj = data?.kvs || {};
      const newObj = {};
      for (const key in originalObj) {
        newObj[originalObj[key]] = originalObj[key];
      }
      return newObj;
    },
  },
  {
    name: 'protocolType',
    label: '设备类型',
    isFilter: true,
    size: 10,
    max: 20,
    seqNumber: 1,
    showInTable: false,
    showInSearch: true,
    type: 'singleSelect',
    dropdownMethod: 'post',
    dropdownPath: '/cgi/idc-tbos-cgi/Common/GetKvDict',
    dropdownQuery: () => ({ dic_type: 'device_type_kv' }),
    dropdownFormatter: (data) => {
      const originalObj = data?.kvs || {};
      const newObj = {};
      for (const key in originalObj) {
        newObj[originalObj[key]] = originalObj[key];
      }
      return newObj;
    },
  }]
  : [{
    name: 'protocolTypeName',
    label: '设备类型',
    isFilter: false,
    size: 10,
    max: 20,
    seqNumber: 1,
    showInTable: true,
    showInSearch: false,
    type: 'singleSelect',
    dropdownMethod: 'post',
    dropdownPath: '/cgi/alarm/rule/getDropdown',
    dropdownQuery: () => ({ field: 'protocolType' }),
  },
  {
    name: 'protocolType',
    label: '设备类型',
    isFilter: true,
    size: 10,
    max: 20,
    seqNumber: 1,
    showInTable: false,
    showInSearch: true,
    type: 'singleSelect',
    dropdownMethod: 'post',
    dropdownPath: '/cgi/alarm/rule/getDropdown',
    dropdownQuery: () => ({ field: 'protocolType' }),
  }];

const v2Columns = [{
  name: 'applicationTypeEn',
  label: '应用类型',
  isFilter: true,
  size: 10,
  max: 20,
  seqNumber: 1,
  showInTable: false,
  showInSearch: true,
  type: 'singleSelect',
  dropdownMethod: 'post',
  dropdownPath: '/cgi/gidmapping/getDeviceTypeDicInfo',
  dropdownQuery: () => ({ typeCode: 2 }),
  dropdownFormatter: data => _.chain(data.dataList)
    .map(item => ([item.typeEn, item.typeZh]))
    .fromPairs()
    .value(),
}, {
  name: 'deviceCategoryEn',
  label: '设备种类',
  isFilter: true,
  size: 10,
  max: 20,
  seqNumber: 1,
  showInTable: false,
  showInSearch: true,
  type: 'singleSelect',
  dropdownMethod: 'post',
  dropdownPath: '/cgi/gidmapping/getDeviceTypeDicInfo',
  dropdownQuery: () => ({ typeCode: 1 }),
  dropdownFormatter: data => _.chain(data.dataList)
    .map(item => ([item.typeEn, item.typeZh]))
    .fromPairs()
    .value(),
}, {
  name: 'applicationTypeZh',
  label: '应用类型',
  size: 10,
  max: 10,
  type: 'pureStringNotArray',
  isFilter: false,
  seqNumber: 2,
  showInTable: true,
  showInSearch: false,
}, {
  name: 'deviceCategoryZh',
  label: '设备种类',
  size: 10,
  max: 10,
  type: 'pureStringNotArray',
  isFilter: false,
  seqNumber: 2,
  showInTable: true,
  showInSearch: false,
}];

export default [
  ...(window.tnwebServices.customConfigService.get('EnableDeviceNumberV2') === '1' ? v2Columns : v1Columns),
  {
    name: 'deviceNumberList',
    label: '设备编号',
    size: 15,
    max: 10,
    type: 'pureStringNotArray',
    isFilter: false,
    seqNumber: 11,
    showInTable: false,
    showInSearch: false,
    placeholder: '请输入',
    formatter(row) {
      return row.deviceNumberList.join(',');
    },
  // fieldEnum: [{ label: 'l1', value: 'l1' }],
  // dropdownMethod: 'post',
  // dropdownPath: '/cgi/alarm/rule/getDropdown',
  // dropdownQuery: () => ({ field: 'protocolType' }),
  },
  {
    name: 'deviceCount',
    label: '设备数量',
    size: 6,
    max: 10,
    type: 'pureStringNotArray',
    isFilter: false,
    seqNumber: 2,
    showInTable: true,
    showInSearch: false,
    placeholder: '请输入',
    formatter(row) {
      return `${row.deviceCount}台`;
    },
  },
  {
    name: 'alarmType',
    label: '告警类型',
    size: 15,
    max: 20,
    isFilter: true,
    type: 'singleSelect',
    seqNumber: 3,
    showInTable: true,
    showInSearch: true,
    dropdownMethod: 'post',
    dropdownPath: '/cgi/alarm/rule/getDropdown',
    dropdownQuery: () => ({ field: 'alarmType' }),
    getColumnStyle: () => ({
      color: '#1470CC',
    }),
  }, {
    name: 'alarmLevel',
    label: '告警等级',
    size: 5,
    max: 20,
    isFilter: true,
    type: 'singleSelect',
    seqNumber: 4,
    showInTable: true,
    showInSearch: true,
    modifyName: true,
    localData: true,
    getColumnStyle: ({ row }) => ({
      padding: '8px 12px',
      'border-radius': '8px',
      'background-color': colorMap[row.alarmLevel],
      color: '#fff',
    }),
    modifyMap: [
      {
        label: '零级',
        value: 'L0',
      }, {
        label: '一级',
        value: 'L1',
      }, {
        label: '二级',
        value: 'L2',
      }, {
        label: '三级',
        value: 'L3',
      }, {
        label: '四级',
        value: 'L4',
      }, {
        label: '五级',
        value: 'L5',
      },
    ],
    fieldSingleEnum: [
      '零级',
      '一级',
      '二级',
      '三级',
      '四级',
      '五级',
    ],
    // dropdownMethod: 'post',
    // dropdownPath: '/cgi/alarm/rule/getDropdown',
    // dropdownQuery: () => ({ field: 'alarmLevel' }),
  },
  {
    name: 'alarmContent',
    label: '告警内容',
    size: 20,
    max: 30,
    isFilter: false,
    type: 'string',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
  },
  {
    name: 'isStandard',
    label: '标准策略',
    size: 5,
    max: 30,
    isFilter: false,
    type: 'singleSelect',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
    localData: true,
    fieldSingleEnum: { true: '是', false: '否' },
    formatter(row) {
      return row.isStandard === true ? '是' : '否';
    },
  },
  // {
  //   name: 'applicableVersion',
  //   label: '适用版本',
  //   size: 8,
  //   max: 30,
  //   isFilter: false,
  //   type: 'string',
  //   seqNumber: 5,
  //   showInTable: true,
  // },
  {
    name: 'occurExpression',
    label: '触发表达式',
    size: 15,
    max: 30,
    isFilter: false,
    type: 'string',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
  },
  // {
  //   name: 'occurPeriod',
  //   label: '触发判断周期',
  //   size: 5,
  //   max: 30,
  //   isFilter: false,
  //   type: 'string',
  //   seqNumber: 5,
  //   showInTable: true,
  //   showInSearch: true,
  // },
  // {
  //   name: 'occurCount',
  //   label: '触发周期内发生次数',
  //   size: 5,
  //   max: 30,
  //   isFilter: false,
  //   type: 'string',
  //   seqNumber: 5,
  //   showInTable: true,
  //   showInSearch: true,
  // },
  {
    name: 'restoreExpression',
    label: '恢复表达式',
    size: 15,
    max: 30,
    isFilter: false,
    type: 'string',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
  },
  // {
  //   name: 'restorePeriod',
  //   label: '恢复周期',
  //   size: 5,
  //   max: 30,
  //   isFilter: false,
  //   type: 'false',
  //   seqNumber: 5,
  //   showInTable: true,
  //   showInSearch: true,
  // },
  // {
  //   name: 'restoreCount',
  //   label: '恢复周期内发生次数',
  //   size: 5,
  //   max: 30,
  //   isFilter: false,
  //   type: 'string',
  //   seqNumber: 5,
  //   showInTable: true,
  //   showInSearch: true,
  // },
  {
    name: 'createdByName',
    label: '创建人',
    size: 10,
    max: 30,
    isFilter: false,
    type: 'singleSelect',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
    dropdownMethod: 'post',
    dropdownPath: '/cgi/alarm/rule/getDropdown',
    dropdownQuery: () => ({ field: 'createdBy' }),
  },
  {
    name: 'createdAt',
    label: '创建时间',
    size: 12,
    max: 30,
    isFilter: false,
    type: 'string',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
  },
  {
    name: 'updatedByName',
    label: '修改人',
    size: 10,
    max: 30,
    isFilter: false,
    type: 'singleSelect',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
    dropdownMethod: 'post',
    dropdownPath: '/cgi/alarm/rule/getDropdown',
    dropdownQuery: () => ({ field: 'updatedBy' }),
  },
  {
    name: 'updatedAt',
    label: '修改时间',
    size: 12,
    max: 30,
    isFilter: false,
    type: 'string',
    seqNumber: 5,
    showInTable: true,
    showInSearch: true,
  },
  {
    name: 'operator',
    label: '操作',
    fixed: 'right',
    size: 9,
    max: 30,
    isFilter: false,
    seqNumber: 11,
    show: true,
    showInTable: true,
    // operationUrl: [{ 转责任人: '/tassets/statistics-asset-detail' }, { 确认工单: '确认工单' }, { 认领: 'c' }],
    operationUrl: [{ operation: '详情', url: 'c', authCode: 'TNJKGL-GJPZ-CK' }, { operation: '编辑', url: 'c', authCode: 'TNJKGL-GJPZ-GL', cloudFlag: !business.showModuleSelected }, { operation: '删除', url: 'c', authCode: 'TNJKGL-GJPZ-GL', cloudFlag: !business.showModuleSelected }],
    operationMap: { 详情: '详情', 编辑: '编辑', 删除: '删除' },
    instantOperation: '详情',
  // jumpQuery: ['asset_id'],
  },
];
