user nginx;
worker_processes 2;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    sendfile on;
    #tcp_nopush     on;
    keepalive_timeout 65;
    gzip on;
    #include /etc/nginx/conf.d/*.conf;

    client_max_body_size 100M; # 测点配置非常大，可能100M还要大
    server {
        # 使用模板变量，启动时会被envsubst替换
        listen ${PORT_WEB};

        location /cgi/idc-tbos-cgi/ {
            proxy_pass http://localhost:${PORT_CGI}/;
            proxy_set_header mozuId $cookie_mozuid;
        }

        location /cgi/idc-tbos-cmdb/ {
            proxy_pass http://localhost:${PORT_CMDB}/;
            proxy_set_header mozuId $cookie_mozuid;
        }

        # 门禁（DAC）服务反向代理
        location /api/dcos/tdac-cgi/ {
            proxy_pass http://localhost:${PORT_DAC}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header mozuId $cookie_mozuid;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
        }

        location / {
            root /usr/share/nginx/html/tnebula/main;
            index index.html index.htm;
        }

        location /static/ {
            root /usr/share/nginx/html/tnebula/main/;
            add_header Cache-Control no-store;
        }

        location =/apps.json {
            root /usr/share/nginx/html/tnebula/main;
            add_header Cache-Control no-store;
        }

        location =/dcim/dist/apps.json {
            root /usr/share/nginx/html/tnebula/main;
            add_header Cache-Control no-store;
        }

        location =/importmap.json {
            root /usr/share/nginx/html/tnebula/main;
            add_header Cache-Control no-store;
        }

        location =/dcim/dist/importmap.json {
            root /usr/share/nginx/html/tnebula/main;
            add_header Cache-Control no-store;
        }

        location ~* \/iframe([^.]+)$ {
            try_files $uri $uri.html $uri/ /iframe.html;
        }

        location ~* \/pad([^.]+)$ {
            try_files $uri $uri.html $uri/ /pad.html;
        }

        location ~* \/tedge([^.]+)$ {
            try_files $uri $uri.html $uri/ /index.html;
        }

        location ^~ /frame {
            alias /usr/share/nginx/html/tnebula/frame/;
            index index.html index.htm;
        }

        location ^~ /microfrontend {
            alias /usr/share/nginx/html/tnebula/microfrontend/;
            index index.html index.htm;
        }
    }
}
